class spiele {
    constructor() {
        this.stadt = [
            "Kabul",
            "Tirana",
            "Algier",
            "Andorra-la-Vella",
            "Luanda",
            " St. John's",
            "Buenos Aires",
            "Eriwan",
            "Baku",
            "Canberra",
            "Wien",
            "Manama",
            "Dhaka",
            "Bridgetown",
            "Minsk",
            "Brüssel",
            "Belmopan",
            "Porto-Novo_(offiziell)",
            "Thimphu",
            " La Paz (administrativ)",
            "Sarajevo",
            "Gaborone",
            "Brasília",
            "Bandar Seri Begawan",
            "Sofia",
            "Ouagadougou",
            "Bujumbura",
            "Phnom Penh",
            "Yaoundé",
            "Ottawa",
            "Praia",
            "Bangui",
            "N_Djamena",
            "Santiago",
            "Peking (als Beijing in Mandarin)",
            "Bogotá",
            "Moroni",
            "Brazzaville",
            "San José",
            "Zagreb",
            "Havanna",
            "Nikosia",
            "Prag",
            "Kopenhagen",
            "Dschibuti Stadt",
            "Roseau",
            "Santo Domingo",
            "Quito",
            "Kairo",
            "San Salvador",
            "Malabo",
            "Asmara",
            "Tallinn",
            "Addis Abeba",
            "Suva",
            "Helsinki",
            "Paris",
            "Libreville",
            "Banjul",
            "Tiflis",
            "Berlin",
            " Accra",
            "Athen",
            'St. George"s',
            "Guatemala Stadt",
            "Conakry",
            "Bissau",
            "Georgetown",
            "Port-au-Prince",
            "Tegucigalpa",
            "Hongkong",
            "Budapest",
            "Reykjavik",
            "Neu-Delhi",
            "Jakarta",
            "Teheran",
            "Bagdad",
            "Dublin",
            "Jerusalem",
            " Rom",
            "Yamoussoukro",
            "Kingston",
            "Tokio",
            "Amman",
            "Nur Sultan",
            "Nairobi",
            "Tarawa",
            "Pjöngjang",
            "Seoul",
            "Pristina",
            "Kuwait-Stadt",
            "Biskek",
            "Vientiane",
            "Riga",
            "Beirut",
            "Maseru",
            "Monrovia",
            "Tripolis",
            "Vaduz",
            "Vilnius",
            "Luxemburg",
            "Macau",
            "Skopje",
            "Antananarivo",
            "Lilongwe",
            "Kuala Lumpur",
            "Malé",
            "Bamako",
            "Valletta",
            "Majuro",
            "Nouakchott",
            "Port Louis",
            "Mexiko-Stadt",
            "Palikir",
            "Chisinau",
            "Monaco",
            "Ulaanbaatar",
            "Podgorica",
            "Rabat",
            "Maputo",
            "Naypyidaw",
            "Windhoek",
            "Yaren",
            "Kathmandu",
            "Amsterdam",
            "Wellington",
            "Managua",
            "Niamey",
            "Abuja",
            "Oslo",
            "Maskat",
            "Islamabad",
            "Melekeok",
            "Panama Stadt",
            "Port Moresby",
            "Asunción",
            " Lima",
            "Manila",
            "Warschau",
            "Lissabon",
            "Doha",
            "Bukarest",
            "Moskau",
            "Kigali",
            "Basseterre",
            "Castries",
            "Kingstown",
            "Apia",
            "San Marino",
            "Sao Tome",
            "Riad",
            "Dakar",
            "Belgrad",
            "Victoria",
            "Freetown",
            "Singapur",
            "Bratislava",
            "Ljubljana",
            "Honiara",
            "Mogadischu",
            "Pretoria (administrative Hauptstadt)",
            "Juba",
            "Madrid",
            "Sri Jayawardenepura Kotte",
            "Khartum",
            "Paramaribo",
            "Mbabane",
            "Stockholm",
            "Bern",
            "Damaskus",
            "Taipeh",
            "Duschanbe",
            "Dodoma",
            "Bangkok",
            " Dili",
            "Lomé",
            "Nuku,alofa",
            "Port of Spain",
            "Tunis",
            "Ankara",
            "Ashgabat",
            "Funafuti",
            "Kampala",
            "Abu Dhabi",
            "London",
            " Washington, D.C.",
            "Montevideo",
            "Taschkent",
            " Port Vila",
            "Vatikanstadt",
            "Caracas",
            "Hanoi",
            "Sanaa",
            "Lusaka",
            "Harare",
            "Doha",
            "Sana'a",
            "China",
            "China",
        ];
        this.länder2 = [
            "Afghanistan",
            "Albanien",
            "Algerien",
            "Andorra",
            "Angola",
            "AntiguaUndBarbuda",
            "Argentinien",
            "Armenien",
            "Aserbaidschan",
            "Australien",
            "Österreich",
            "Bahrain",
            "Bangladesch",
            "Barbados",
            "Weißrussland",
            "Belgien",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivien",
            "BosnienHerzegowina",
            "Botsuana",
            "Brasilien",
            "Brunei",
            "Bulgarien",
            "BurkinaFaso",
            "Burundi",
            "Kambodscha",
            "Kamerun",
            "Kanada",
            "KapVerde",
            "ZentralAfrikanischeRepublik",
            "Tschad",
            "Chile",
            "China",
            "Kolumbien",
            "Komoren",
            "Kongo",
            "CostaRica",
            "Kroatien",
            "Kuba",
            "Zypern",
            "TschechischeRepublik",
            "Dänemark",
            "Dschibuti",
            "Dominica",
            "DominikanischeRepublik",
            "Ecuador",
            "Ägypten",
            "ElSalvador",
            "Äquatorialguinea",
            "Eritrea",
            "Estland",
            "Äthiopien",
            "Fidschi",
            "Finnland",
            "Frankreich",
            "Gabun",
            "Gambia",
            "Georgien",
            "Deutschland",
            "Ghana",
            "Griechenland",
            "Grenada",
            "Guatemala",
            "Guinea",
            "GuineaBissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hongkong",
            "Ungarn",
            "Island",
            "Indien",
            "Indonesien",
            "Iran",
            "Irak",
            "Irland",
            "Israel",
            "Italien",
            "Elfenbeinküste",
            "Jamaika",
            "Japan",
            "Jordanien",
            "Kasachstan",
            "Kenia",
            "Kiribati",
            "Nordkorea",
            "Südkorea",
            "Kosovo",
            "Kuwait",
            "Kirgisistan",
            "Laos",
            "Lettland",
            "Libanon",
            "Lesotho",
            "Liberia",
            "Libyen",
            "Liechtenstein",
            "Litauen",
            "Luxemburg",
            "Macau",
            "Mazedonien",
            "Madagaskar",
            "Malawi",
            "Malaysia",
            "Malediven",
            "Mali",
            "Malta",
            "Marshallinseln",
            "Mauretanien",
            "Mauritius",
            "Mexiko",
            "Mikronesien",
            "Moldawien",
            "Monaco",
            "Mongolei",
            "Montenegro",
            "Marokko",
            "Mosambik",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Niederlande",
            "Neuseeland",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Norwegen",
            "Oman",
            "Pakistan",
            "Palau",
            "Panama",
            "Papua_Neuguinea",
            "Paraguay",
            "Peru",
            "Philippinen",
            "Polen",
            "Portugal",
            "Katar",
            "Rumänien",
            "Russland",
            "Ruanda",
            "Saint_Kitts_Nevis",
            "Saint_Lucia",
            "Saint_Vincent_die_Grenadinen",
            "Samoa",
            "San_Marino",
            "Sao_Tome_Principe",
            "Saudi_Arabien",
            "Senegal",
            "Serbien",
            "Seychellen",
            "Sierra_Leone",
            "Singapur",
            "Slowakei",
            "Slovenien",
            "Salomonen",
            "Somalia",
            "Südafrika",
            "Südsudan",
            "Spanien",
            "Sri_Lanka",
            "Sudan",
            "Surinam",
            "Swasiland",
            "Schweden",
            "Schweiz",
            "Syrien",
            "Taiwan",
            "Tadschikistan",
            "Tansania",
            "Thailand",
            "Osttimor",
            "Togo",
            "Tonga",
            "Trinidad_Tobago",
            "Tunesien",
            "Türkei",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Vereinigte_Arabische_Emirate",
            "Großbritannien",
            "USA",
            "Uruguay",
            "Usbekistan",
            "Vanuatu",
            "Vatikanstadt",
            "Venezuela",
            "Vietnam",
            "Jemen",
            "Zambia",
            "Simbabwe",
            "Qatar(Katar)",
            "Yamen",
            "Xuzhou",
            "Xiamen",
        ];
        this.flusse = [
            "Amazonas",
            "Xar Moron",
            "Xiliao He",
            "Nil",
            "Yangtze",
            "Mississippi",
            "Danube",
            "Yenisei",
            "Yellow River",
            "Congo",
            "Paraná",
            "Indus",
            "Ganges",
            "Murray",
            "Volga",
            "Rhine",
            "Mekong",
            "Colorado",
            "Qiantang",
            "Orinoco",
            "Tigris",
            "Brahmaputra",
            "Hudson",
            "Thames",
            "Jordan",
            "St.Lawrence",
            "Yarra",
            "Irrawaddy",
            "Rhein",
            "Seine",
            "Donau",
            "Ob",
            "Rhône",
            "Ebro",
            "Po",
            "Elbe",
            "Tiber",
            "Douro",
            "Loire",
            "Dnjepr",
            "Lena",
            "Ural",
            "Isère",
            "Savannah",
            "Sacramento",
            "Euphrat",
            "Shatt",
            "Niger",
            "Zambezi",
            "Amur",
            "Columbia",
            "Huai",
            "Rio_Grande",
            "Yellowstone",
            "Rio de la Plata",
            "Murray-Darling",
            "Mackenzie",
            "Missouri",
            "Vistula",
            "São Francisco",
            "Rio Paraná",
            "Arno",
            "Syr Darya(",
            "Indigirka(Russland)",
            "Rio de Janeiro",
            "Rhone",
            "Rio Negro",
            "Kolyma",
            "Rio Formoso",
            "Rio Sucuri",
            "Rio Xingu",
            "Rio Araguaia",
            "Rio Tocantins",
            "Rio Madeira",
            "Rio São Francisco",
            "Rio Colorado",
            "Rio Paraná Guazú",
            "Rio Uruguay",
            "Rio Pilcomayo",
            "Rio Bermejo",
            "Rio Baker",
            "Rio Loa",
            "Rio Maipo",
            "Rio Claro",
            "Rio Limari",
            "Rio Aconcagua",
            "Rio Mapocho",
            "Rio Tolten",
            "Rio Itata",
            "Rio Biobío",
            "Rio Imperial",
            "Rio Cruces",
            "Rio Valdivia",
            "Rio Nuble",
            "Rio Laja",
            "Rio Yali",
            "Rio Choapa",
            "Rio Petorca",
            "Rio Quillota",
            "Rio Cachapoal",
            "Rio Rapel",
            "Rio Mataquito",
            "Rio Teno",
            "Rio Huallaga",
            "Rio Ucayali",
            "Rio Marañon",
            "Rio Amazonas",
            "Rio Napo",
            "Rio Putumayo",
            "Rio Orinoco",
            "Rio Magdalena",
            "Rio Caquetá",
            "Rio Atrato",
            "Rio Patía",
            "Rio Cauca",
            "Rio Sinú",
            "Rio Quito",
            "Rio Guayas",
            "Rio Pastaza",
            "Rio Coca",
            "Rio Paraguay",
            "Rio Apa",
            "Rio Iguaçu",
            "Rio Doce",
            "Rio Parnaíba",
            "Rio Jacuí",
            "Rio Grande",
            "Rio Solimões",
            "Rio Juruá",
            "Rio Purus",
            "Rio São_Francisco",
            "Rio Itajaí",
            "Rio Tibagi",
            "Riode la Plata)",
            "Rio Missouri",
            "Rio Columbia",
            "Rio Snake",
            "Rio Mississippi",
            "Rio Ohio",
            "Rio Cumberland",
            "Rio Tennessee",
            "Rio Yazoo",
            "Rio Red",
            "Rio Arkansas",
            "Rio Trinity",
            "Rio Brazos",
            "Rio Guadalupe",
            "Rio Rio Grande",
            "Rio Pecos",
            "Rio Yukon",
            "Rio Mackenzie",
            "Rio St.Lawrence",
            "Rio Nelson",
            "Rio Fraser",
            "Rio Skeena",
            "Rio Athabasca",
            "Rio Peace",
            "Rio Churchill",
            "Rio Liard",
            "Rio Coppermine",
            "Rio Hayes",
            "Rio Rideau",
            "Rio Ottawa",
            "Rio St.John",
            "Severn",
            "Trent",
            "Tyne",
            "Dee",
            "Clyde",
            "Avon",
            "Mersey",
            "Humber",
            "Tees",
            "Forth",
            "Tweed",
            "Tamar",
            "Exe",
            "Ouse ",
            "Wear ",
        ];
        this.namen = [
            "Emma",
            "Mia",
            "Sophia",
            "Olivia",
            "Isabella",
            "Ava",
            "Lily",
            "Zoe",
            "Charlotte",
            "Amelia",
            "Harper",
            "Evelyn",
            "Abigail",
            "Aria",
            "Aaliyah",
            "Scarlett",
            "Riley",
            "Paul",
            "Ella",
            "Peter",
            "Philipp",
            "Patricia",
            "Pamela",
            "Penelope",
            "Patrick",
            "Paige",
            "Percy",
            "Xavier",
            "Xander",
            "Ximena",
            "Xiomara",
            "Xaver",
            "Priscilla",
            "Addison",
            "Elizabeth",
            "Sofia",
            "Avery",
            "Elliana",
            "Grace",
            "Victoria",
            "Madison",
            "Chloe",
            "Layla",
            "Rylee",
            "Aubrey",
            "Adalynn",
            "Adalyn",
            "Hazel",
            "Nora",
            "Willa",
            "Luna",
            "Kennedy",
            "Mackenzie",
            "Sadie",
            "Peyton",
            "Ellie",
            "Nova",
            "Leah",
            "Audrey",
            "Skylar",
            "Naomi",
            "Camila",
            "Anna",
            "Ariana",
            "Allison",
            "Caroline",
            "Genesis",
            "Madelyn",
            "Adeline",
            "Maya",
            "Aubree",
            "Kaylee",
            "Sarah",
            "Natalie",
            "Brooklyn",
            "Zoey",
            "Elaina",
            "Brianna",
            " Jasmine",
            "Westlynn",
            "Autumn",
            "Mariah",
            "Ruby",
            "Ellis",
            "Mila",
            "Finley",
            "Kennedi",
            "Annabelle",
            "Paisley",
            "Presley",
            "Michaela",
            " Eloise",
            "Rowan",
            "Josephine",
            "Delilah",
            "Julianna",
            "Alaina ",
            "Una",
            "Quentin",
            "Quinn",
            "Quirin",
            "Quirina",
            "Quirinus",
            "Quoc",
            "Qiana",
            "Qadir",
            "Qasim",
            "Uriel",
            "Uliana",
            "Ugo",
            "Ulises",
            "Upton",
            "Uzair",
            "Umair",
            "Unaiza",
            "Umar",
            "Ursula",
            "Udo",
            "Ulrich",
            "Ulla",
            "Ute",
            "Ulrike",
            "Ulf",
            "Uwe",
            "Uschi",
            "Urban",
            " Rylee",
            "Jasmine ",
            "Eloise",
            "Alaina",
            "Adalynn ",
            "Paisley ",
            "Presley ",
            " Sarah",
            "Isabelle",
            "Lillian",
            "Lulu",
            "Freya",
            "Elsie",
            "Eleanor",
            "Aurora",
            "Alexander",
            "William",
            "Benjamin",
            "Henry",
            "Samuel",
            "Oliver",
            "George",
            "Felix",
            "Liam",
            "Maximilian",
            "Jasper",
            "Owen",
            "Louis",
            "Victor",
            "Leo",
            "Caleb",
            "Oscar",
            "Felix (Latein)",
            "Benjamin ",
            "Ethan ",
            "James",
            "Joseph",
            "Matthew",
            "Daniel",
            "Andrew",
            "David",
            "Christopher",
            "Nathan",
            "Jack",
            "Nicholas",
            "Tyler",
            "Ryan",
            "Adam",
            "Jonathan",
            "Zachary",
            "Justin",
            "Thomas",
            "Evan",
            "Luke",
            "Mason",
            "Gabriel",
            "Isaac",
            "Michael",
            "Dylan",
            "Joshua",
            "Christian",
            "Elijah",
            "Aaron",
            "Connor",
            "Juan",
            "Adrian",
            "Travis",
            "Jordan",
            "Kyle",
            "Landon",
            "Austin",
            "Jared",
            "Brandon",
            "Jason",
            "Ethan",
            "Noah",
            "Jacob",
            "John",
            "Robert",
            "Kevin",
            "Charles",
            "Mark",
            "Richard",
            "Brian",
            "Brian ",
            "Thomas)",
            "Youssef",
            "Yvonne",
            "Yasmin",
            "Yves",
            "Yannick",
            "Yara",
            "Yannis",
            "Yael",
            "Yvette",
            "Yale",
            "Yuri",
        ];
        this.hausHalts = [
            "Abfalleimer",
            "Akkuschrauber",
            "Apfelentkerner",
            "Armlehnstuhl",
            "Aschenbecher",
            "Aufbewahrungsbox",
            "Auflaufform",
            " Ausstechform",
            "Teller",
            "Schüsseln",
            "Tassen",
            "Gläser",
            "Besteck",
            "Messer",
            "Gabeln",
            "Löffel",
            "Kochlöffel",
            "Pfannenwender",
            "Pfannen",
            "Töpfe",
            "Bräter",
            "Backbleche",
            "Schneidebretter",
            "Scheren",
            "Schäler",
            "Kartoffelstampfer",
            "Spülbürste",
            "Staubsauger",
            "Besen",
            "Handfeger",
            "Wischmop",
            "Putzeimer",
            "Putzlappen",
            "Reinigungsspray",
            "Geschirrspülmittel",
            "Waschmaschine",
            "Trockner",
            "Bügeleisen",
            "Bügelbrett",
            "Kleiderbügel",
            "Bettwäsche",
            "Handtücher",
            "Kissen",
            "Decken",
            "Lampen",
            "Steckdosen",
            "Verlängerungskabel",
            "Elektrorasierer",
            "Haartrockner",
            "Glätteisen",
            "Lockenstab",
            "Zahnbürste",
            "Zahnpasta",
            "Seife",
            "Shampoo",
            "Conditioner",
            "Duschgel",
            "Handseife",
            "Toilettenpapier",
            "Taschentücher",
            "Papierhandtücher",
            "Müllbeutel",
            "Mülleimer",
            "Schaufel",
            "Schrubber",
            "Gartenschlauch",
            "Gartenschere",
            "Rasenmäher",
            "Laubbläser",
            "Fahrrad",
            "Rollschuhe",
            "Skateboard",
            "Inline-Skates",
            "Tisch",
            "Stühle",
            "Sofa",
            "Sessel",
            "Regale",
            "Betten",
            "Schränke",
            "Kommode",
            "Fernseher",
            "Computer",
            "Tastatur",
            "Maus",
            "Drucker",
            "Scanner",
            "Kaffeemaschine",
            "Toaster",
            "Wasserkocher",
            "Mikrowelle",
            "Backofen",
            "Herd",
            "Kühlschrank",
            "Gefrierschrank",
            "Geschirrspüler",
            "Nähmaschine",
            "Bücherregal",
            "Vasen",
            "Kerzenhalter",
            "Spiegel",
            "Gardinen",
            "Teppiche",
            "Lampenschirme",
            "Teelichter",
            "Gartenmöbel",
            "Briefkasten",
        ];
        this.pflanze = [
            "Zierlauch ",
            "Zitronenbaum ",
            "Zierquitte ",
            "Zaubernuss ",
            "Zimtbaum ",
            "Zucchini ",
            "Zwergmispel ",
            "Zwergginster ",
            "Zitronenmelisse ",
            "Zypressen",
            "Ananas",
            "Aloe Vera",
            "Apfelbaum",
            "Avocado",
            "Bambus",
            "Bananenstaude",
            "Basilikum",
            "Begonie",
            "Birnbaum",
            "Ahornbaum",
            "Blaubeere",
            "Blumenkohl",
            "Brombeere",
            "Buschbohne",
            "Buschpfeffer",
            "Chili",
            "Dahlie",
            "Dattelpalme",
            "Distel",
            "Efeu",
            "Eichenbaum",
            "Eisenhut",
            "Erdbeere",
            "Eukalyptus",
            "Farn",
            "Feige",
            "Fenchel",
            "Fingerhut",
            "Flieder",
            "Gerbera",
            "Gerste",
            "Ginster",
            "Goldregen",
            "Gras",
            "Usambaraveilchen",
            "Urwaldrebe",
            "Ufer-Wolfstrapp",
            "Ulme (Ulmus)",
            "Ufer-Binse (Juncus)",
            "Usambarazwergpalme ",
            "Unsterblichkeitskraut ",
            "Unterseeische Grasnelke ",
            "Urwaldpfeffer ",
            "Gurke",
            "Xanthorrhoea",
            "Xeranthemum",
            "Xyris",
            "Xenophyllum ",
            "Haselnussbaum",
            "Heidekraut",
            "Himbeere",
            "Hortensie",
            "Hyazinthe",
            "Ingwer",
            "Jasmin",
            "Johannisbeere",
            "Kaktus",
            "Kamille",
            "Kapernstrauch",
            "Kartoffel",
            "Kiefernbaum",
            "Kirschbaum",
            "Knoblauch",
            "Kohl",
            "Krokus",
            "Kürbis",
            "Lavendel",
            "Leinsamen",
            "Löwenzahn",
            "Magnolie",
            "Malve",
            "Mandelbaum",
            "Mango",
            "Maulbeere",
            "Meerrettich",
            "Melone",
            "Minze",
            "Mohrrübe",
            "Narzisse",
            "Nelke",
            "Olive",
            "Orchidee",
            "Paprika",
            "Papaya",
            "Papyrus",
            "Passionsblume",
            "Pfefferminze",
            "Pflaumenbaum",
            "Pinie",
            "Quitte",
            "Radieschen",
            "Raps",
            "Rhabarber",
            "Rhododendron",
            "Ringelblume",
            "Rosmarin",
            "Rotklee",
            "Safran",
            "Salbei",
            "Schachtelhalm",
            "Schlehdorn",
            "Schneeglöckchen",
            "Schwarzer Holunder",
            "Sonnenblume",
            "Spargel",
            "Spinat",
            "Stiefmütterchen",
            "Tabakpflanze",
            "Thymian",
            "Tomate",
            "Traubenbaum",
            "Wacholder",
            "Yucca-Palme",
            "Yakushi-Girlandenblume",
            "Ysop",
            "Yelapa-Salbei",
            "Yilan-Kiefer",
            "Ylang-Ylang-Baum",
            "Yebisu-Bambus",
            "Yerba-Buena",
            "Yellowwood-Baum ",
            "Yoko-Bambus",
        ];
        this.tier = [
            "Pottwal",
            "Xenopus",
            "Orcinus_orca_(Schwertwal)",
            "Großer_Tümmler",
            "Weißseitendelfin",
            "Gemeiner_Delfin",
            "Buckelwal",
            "Finnwal",
            "Brydewal",
            "Seiwal",
            "Blauwal",
            "Schweinswal",
            "Utah-Klippschliefer",
            "Umbrellavogel",
            "Usambaraveilchenaffe",
            "Ussurischer Tiger",
            "Uhuwachtel",
            "Uromastyx (Wüstendornschwanz)",
            "Utahraptor",
            "Ussurikatze",
            "Ufermaus",
            "Unterirdischer Hundsfisch",
            "Irrawaddy-Delfin",
            "Indischer Flussdelphin",
            "Ganges-Delfin",
            "Vaquita",
            "Gewöhnlicher Schweinswal",
            "Rundkopfdelfin",
            "Kurzflossen-Grindwal",
            "Langflossen-Grindwal",
            "Streifendelfin",
            "Rauzahndelfin",
            "Zwergwal",
            "Hector-Delfin",
            "Kleiner Schwertwal",
            "Indopazifischer Großer Tümmler",
            "Dusky-Delfin",
            "Glattwal",
            "Beluga",
            "Grauwal",
            "Nordkaper",
            "Südkaper",
            "Pudú-Delfin",
            "Risso-Delfin",
            "Baird-Beaked-Wal",
            "Uhu",
            "Urang-Utan",
            "Uakari",
            "Uferläufer",
            "Uferschnepfe",
            "Unke",
            "Urial",
            "Urraca",
            "Unterwasserfliege",
            "Tucuxi",
            "Weißflanken-Delfin",
            "Atlantischer Delfin",
            "Dall-Delfin",
            "Chile-Delfin",
            "Commerson-Delfin",
            "Amazonas-Delfin",
            "Indischer Ozean Grindwal",
            "Fraser-Delfin",
            "Geomys-Delfin",
            "Schwarzdelfin",
            "Südlicher Glattwal",
            "Tümmler der Nordostküste von Schottland",
            "Langschwanzdelfin",
            "Hourglass-Delfin",
            "Atlantic Humpback Dolphin",
            "Indischer Ozean Delfin",
            "Delfin von Guadalupe",
            "Atlantik-Grauflossen-Delfin",
            "Blau-Weiße-Delfin",
            "Northern Right Whale Dolphin",
            "Zügeldelfin",
            "Spitzkopfdelfin",
            "Borneo-Delfin",
            "Spinner-Delfin",
            "Clymene-Delfin",
            "Burmeister-Delfin",
            "Schwarzschnauzen-Delfin",
            "La-Plata-Delfin",
            "Gervais-Delfin",
            "Peale's Dolphin",
            "Atlantic Spotted Dolphin",
            "Fraser's Dolphin",
            "Gray's Spinner Dolphin",
            "Heaviside's Dolphin",
            "Hector's Beaked Whale",
            "Melon-Headed Whale",
            "Northern Bottlenose Whale",
            "Pacific White-Sided Dolphin",
            "Pantropical Spotted Dolphin",
            "Pygmy Killer Whale",
            "Pygmy Sperm Whale",
            "Risso's Dolphin",
            "Rough-Toothed Dolphin",
            "Short-Beaked Common Dolphin",
            "Southern Bottlenose Whale",
            "Southern Hemisphere Humpback Dolphin",
            "Southern Right Whale Dolphin",
            "Spectacled Porpoise",
            "Spotted Dolphin",
            "Striped Dolphin",
            "Ganges River Dolphin",
            "Dusky Dolphin",
            "Indo-Pacific Humpback Dolphin",
            "Long-Finned Pilot",
            "Gemeine Großohrfledermaus",
            "Langflügelfledermaus",
            "Wasserfledermaus",
            "Breitflügelfledermaus",
            "Mopsfledermaus",
            "Bartfledermaus",
            "Graue Langzungenfledermaus",
            "Kleine Hufeisennase",
            "Abendsegler",
            "Fransenlippenfledermaus",
            "Kleiner Abendsegler",
            "Zweifarbfledermaus",
            "Breitflügel-Fruchtvampir",
            "Rotflügel-Fruchtvampir",
            "Flughund",
            "Kahle Fledermaus",
            "Saddleback Fledermaus",
            "Big Brown Fledermaus",
            "Gelbe Fledermaus",
            "Braune Fledermaus",
            "Myotis Lucifugus",
            "Große Abendsegler",
            "Mückenschreck",
            "Riesengleithörnchen",
            "Zwergflughund",
            "Spitzenflügelfledermaus",
            "Kurzschnauzenflughund",
            "Falsche Vampirfledermaus",
            "Nacktschwanz-Rundblattnase",
            "Gould-Fruchttaube",
            "Blassgesicht-Blütenfledermaus",
            "Borneo-Pustelfledermaus",
            "Seba's Kurzohrfledermaus",
            "Jamaicaner Fledermaus",
            "Korsischer Hufeisennase",
            "Felsenkänguru",
            "Pallid Fledermaus",
            "Silberfledermaus",
            "Langnasen-Fruchtvampir",
            "Größerer Knochenflügelfledermaus",
            "Weißrückengleithörnchen",
            "Nördliche Fledermaus",
            "Thailändische Rundblattnase",
            "Große Rundblattnase",
            "Brandts Fledermaus",
            "Waldmurmeltier",
            "Wiesenfledermaus",
            "Diademflughund",
            "Ockerflügelfledermaus",
            "Atlantische Flughund",
            "Nordamerikanischer Flussotter",
            "Rosafarbene Spitzmausfledermaus",
            "Rote Fledermaus",
            "Große Braune Fledermaus",
            "Chinesischer Glattnasenfledermaus",
            "Kastanienbraune Fledermaus",
            "Sri-Lanka-Fruchttaube",
            "Rotrückenfruchttaube",
            "Nördlicher Wollaffe",
            "Yuma Myotis",
            "Graue Großohrfledermaus",
            "Langnasen-Blütenfledermaus",
            "Gewöhnlicher Kinnblattnasenfledermaus",
            "Großohriges Känguru",
            "Schwarzflügel-Fruchtvampir",
            "Jamaikanische Fruchtvampirfledermaus",
            "Bienen",
            "Wespen",
            "Schmetterlinge",
            "Raupen",
            "Käfer",
            "Grashüpfer",
            "Heuschrecken",
            "Schaben",
            "Spinnen",
            "Skorpione",
            "Tausendfüßer",
            "Kakerlaken",
            "Termiten",
            "Libellen",
            "Asseln",
            "Fliegen",
            "Stechmücken",
            "Zecken",
            "Blattläuse",
            "Marienkäfer",
            "Ohrwürmer",
            "Schmetterlingsraupen",
            "Silberfische",
            "Springschwänze",
            "Zebraspinnen",
            "Riesenvogelspinnen",
            "Dornfinger",
            "Kraken",
            "Garnelen",
            "Krebse",
            "Seesterne",
            "Seeigel",
            "Schnecken",
            "Muscheln",
            "Tintenfische",
            "Quallen",
            "Anemonen",
            "Korallen",
            "Schwämme",
            "Seepferdchen",
            "Tintenfischseiche",
            "Hummer",
            "Langusten",
            "Krabben",
            "Tintenfischartige",
            "Schlangensterne",
            "Flamingoseidechsen",
            "Chamäleons",
            "Skorpionspinnen",
            "Seeanemonen",
            "Meeresschlangen",
            "Seeschlangen",
            "Gottesanbeterinnen",
            "Blattschneiderameisen",
            "Falterfische",
            "Rotfeuerfische",
            "Drachenköpfe",
            "Barrakudas",
            "Seeohren",
            "Einsiedlerkrebse",
            "Teufelskrabben",
            "Seepocken",
            "Krustentiere",
            "Eidechsen",
            "Nacktschnecken",
            "Kreuzspinnen",
            "Trichterspinnen",
            "Hausmäuse",
            "Feldmäuse",
            "Wasserflöhe",
            "Schwertlilien",
            "Regenwürmer",
            "Flusskrebse",
            "Flusspferdkrabben",
            "Schlammspringer",
            "Schlammschnecken",
            "Dornenkronenseesterne",
            "Kröten",
            "Frösche",
            "Seefüchse",
            "Feuerwanzen",
            "Schildläuse",
            "Laufkäfer",
            "Eintagsfliegen",
            "Schnaken",
            "Mückenlarven",
            "Springspinnen",
            "Milben",
            "Asselkrebse",
            "Assel",
            "Landkrabben",
            "Langschwanzmakaken",
            "Kaiserkrabben",
            "Riesenassel",
            "Känguru",
            "Wallaby",
            "Koala",
            "Wombat",
            "Tasmanischer Teufel",
            "Opossum",
            "Beutelratte",
            "Bilchbeutler",
            "Kletterbeutler",
            "Ringelschwanz-Filander",
            "Fadenschwanzbeutler",
            "Kurzschnabeligel",
            "Langschnabeligel",
            "Schnabeligel",
            "Zwergbeutelmarder",
            "Schnabeltier",
            "Nasenbeutler",
            "Bergkänguru",
            "Buschkänguru",
            "Gelbfuß-Felskänguru",
            "Roter Riesenkänguru",
            "Schwarznasenkänguru",
            "Baumkänguru",
            "Graukänguru",
            "Riesengleitbeutler",
            "Brauner Gleitbeutler",
            "Zuckertütenbaumkänguru",
            "Rotes Rattenkänguru",
            "Tasmanischer Fuchs",
            "Neuguinea-Kurzkopfbeutler",
            "Ameisenbeutler",
            "Haarschwanz-Rattenkänguru",
            "Spitzkopf-Felsenkänguru",
            "Mahagonibaumkänguru",
            "Östlicher Grauer Riesenkänguru",
            "Krokodilschwanzskink",
            "Krokodilwaran",
            "Grünleguan",
            "Kragenechse",
            "Krokodilkopfgecko",
            "Waran",
            "Leguan",
            "Gila-Krustenechse",
            "Halsbandleguan",
            "Grünschwanzleguan",
            "Pantherchamäleon",
            "Köhlerschildkröte",
            "Karettschildkröte",
            "Lederschildkröte",
            "Grüne Meeresschildkröte",
            "Schwarze Königsnatter",
            "Königskobra",
            "Teppichpython",
            "Grüner Leguan",
            "Sumpfschildkröte",
            "Wüstenschildkröte",
            "Südlicher Höckerschildkröte",
            "Australischer Pythong",
            "Pazifischer Lederschildkröte",
            "Riesenschildkröte",
            "Mangrovenpython",
            "Gelbkopfschildkröte",
            "Echte Geckos",
            "Neuguinea-Waldkänguru",
            "Beutelwolf",
            "Bandikut",
            "Tüpfelbeutelmarder",
            "Südamerikanischer Opossum",
            "Numbat",
            "Aardwolf",
            "Biberkänguru",
            "Flusspferd",
            "Biber",
            "Bisamratte",
            "Dachsbeutel",
            "Kaninchenkänguru",
            "Potoroo",
            "Phalanger",
            "Fettschwanzkänguru",
            "Rüsselratte",
            "Beutelhase",
            "Beutelmaus",
            "Kurzschnauzenbeutelratte",
            "Nacktnasenwombat",
            "Südamerikanischer O",
        ];
        this.beruf = [
            "Astronom",
            "Arzt",
            "Lehrer",
            "Ingenieur",
            "Krankenschwester",
            "Anwalt",
            "Architekt/Architektin",
            "Buchhalter/Buchhalterin",
            "Schriftsteller/Schriftstellerin",
            "Programmierer/Programmiererin",
            "Designer/Designerin",
            "Handwerker/Handwerkerin",
            "Verkäufer/Verkäuferin",
            "Koch/Köchin",
            "Polizist/Polizistin",
            "Künstler/Künstlerin",
            "Musiker/Musikerin",
            "Psychologe/Psychologin",
            "Zahnarzt/Zahnärztin",
            "Fotograf/Fotografin",
            "Journalist/Journalistin",
            "Archäologe/Archäologin",
            "Biologe/Biologin",
            "Xerox-Kopierer-Techniker",
            "XML-Entwickler",
            "Xylofonist",
            "X-Ray-Techniker",
            "Chemiker",
            "Mathematiker",
            "Optiker/in",
            "Orthopädietechniker/in",
            "Orthoptist/in",
            "Onkologe/Onkologin",
            "Organisationsentwickler/in",
            "Objektmanager/in",
            "Offsetdrucker/in",
            "Opernsänger/in",
            "Osteopath/in",
            "Obstbauer",
            "Physiker",
            "Geologin",
            "Geographin",
            "Meteorologe",
            "Ökonomin",
            "Soziologe",
            "Historikerin",
            "Anthropologe",
            "Linguistin",
            "Sozialarbeiter",
            "Umweltwissenschaftler",
            "Agrarwissenschaftler",
            "Krankenhausadministrator",
            "Betriebswirt",
            "Steuerberater",
            "Elektrikerin",
            "Klempnerin",
            "Zimmermann",
            "Maurer",
            "Tischler",
            "Schneider",
            "Metzger",
            "Bäcker",
            "Friseu",
            "Kosmetiker",
            "Reiseleiter",
            "Hotelmanager",
            "Restaurantbesitzer",
            "Weinbauer",
            "Landschaftsgärtner",
            "Mechaniker/",
            "Automechanike",
            "Flugzeugmechaniker",
            "Schiffsbauer",
            "Schmied",
            "Goldschmied",
            "Juwelier",
            "Textildesigner",
            "Modedesigner",
            "Schauspieler",
            "Regisseur",
            "Kameramann",
            "Stuntman",
            "Make-up Artist",
            "Maskenbildnerin",
            "Filmproduzentin",
            "Drehbuchautorin",
            "Sounddesignerin",
            "Grafikdesignerin",
            "Werbetexterin",
            "Marketingmanagerin",
            "Unternehmensberaterin",
            "Personalberaterin",
            "Versicherungsvertreterin",
            "Banker",
            "Vermögensverwalter",
            "Finanzanalyst/Finanzanalystin",
            "Aktienhändler/Aktienhändlerin",
            "Immobilienmakler/Immobilienmaklerin",
            "Bauingenieur/Bauingenieurin",
            "Umweltingenieur/Umweltingenieurin",
            "Maschinenbauingenieur/Maschinenbauingenieurin",
            "Elektroingenieur/Elektroingenieurin",
            "Luft- und Raumfahrtingenieur/Luft- und Raumfahrtingenieurin",
            "Informatiker/Informatikerin",
            "Webentwickler/Webentwicklerin",
            "Datenbankadministrator/Datenbankadministratorin",
            "Netzwerkadministrator/Netzwerkadministratorin",
            "Systemadministrator/Systemadministratorin",
            "IT-Sicherheitsexperte/IT-Sicherheitsexpertin",
            "Unternehmensjurist/Unternehmensjuristin",
            "Arbeitsrechtler/Arbeitsrechtlerin",
            "Strafverteidiger/Strafverteidigerin",
            "Notar/Notarin",
            "Steuerfachmann/Steuerfachfrau",
            "Hausmeister/Hausmeisterin",
            "Gärtner/Gärtnerin",
            "Tierarzt/Tierärztin",
            "Tierpfleger/Tierpflegerin",
            "Lehrer für spezielle Bedürfnisse/Lehrerin für spezielle Bedürfnisse",
            "Sozialpädagoge/Sozialpädagogin",
            "Erzieher/Erzieherin",
            "Hebamme",
            "Physiotherapeut/Physiotherapeutin",
            "Ergotherapeut/Ergotherapeutin",
            "Logopäde/Logopädin",
            "Krankenhausapotheker/Krankenhausapothekerin",
            "Apotheker/Apothekerin",
            "Laborant/Laborantin",
            "Chemielaborant/Chemielaborantin",
            "Biotechnologe/Biotechnologin",
            "Ökotrophologe/Ökotrophologin",
            "Ernährungsberater/Ernährungsberaterin",
            "Sporttrainer/Sporttrainerin",
            "Personal Trainer/Personal Trainerin",
            "Fitnesstrainer/Fitnesstrainerin",
            "Yoga-Lehrer/Yoga-Lehrerin",
            "Pilates-Lehrer/Pilates-Lehrerin",
            "Zumba-Instruktor/Zumba-Instruktorin",
            "DJ",
            "Qualitätskontrolleur/in",
            "Quantenphysiker/in",
            "Quereinsteiger/in",
            "Quick-Response-Manager/in",
            "Quartiermeister/in",
            "Quotenfrau/-mann",
            "Qualitätsmanager/in",
            "Querdenker/in",
            "Qualifizierungstrainer/in",
            "Quelltextprogrammierer/in",
            "Eventplaner/Eventplanerin",
            "Hochzeitsplaner/Hochzeitsplanerin",
            "Rechtsanwaltsfachangestellte/Rechtsanwaltsfachangestellter",
            "Steuerfachangestellte/Ste",
        ];
        this.autos = [
            "Acura",
            "Xenia",
            "Xpeng",
            "Opel ",
            "Alfa Romeo",
            "Aston Martin",
            "Audi",
            "Qiantu K50",
            "Bentley",
            "BMW",
            "Bugatti",
            "Buick",
            "Cadillac",
            "Chevrolet",
            "Chrysler",
            "Citroen",
            "Dodge",
            "Ferrari",
            "Fiat",
            "Ford",
            "Genesis",
            "GMC",
            "Honda",
            "Hummer",
            "Hyundai",
            "Infiniti",
            "Jaguar",
            "Jeep",
            "Kia",
            "Koenigsegg",
            "Lamborghini",
            "Land Rover",
            "Lexus",
            "Lincoln",
            "Lotus",
            "UAZ Patriot",
            "Ultima GTR",
            "Unicorn Ascot",
            "Unimog",
            "Uriel Ventris",
            "Urbee 2",
            "URSUS C-385",
            "UAZ-469",
            "UMM Alter II",
            "Union Cycliste Internationale (UCI)",
            "Maserati",
            "Mazda",
            "McLaren",
            "Mercedes-Benz",
            "Mini",
            "Mitsubishi",
            "Nissan",
            "Pagani",
            "Peugeot",
            "Pininfarina",
            "Plymouth",
            "Polestar",
            "Pontiac",
            "Porsche",
            "Ram",
            "Renault",
            "Rimac",
            "Rolls-Royce",
            "Saab",
            "Saleen",
            "Saturn",
            "Scion",
            "Seat",
            "Skoda",
            "Smart",
            "Spyker",
            "Yema",
            "Youngman",
            "Yutong",
            "SsangYong",
            "Subaru",
            "Suzuki",
            "Tatra",
            "Tesla",
            "Toyota",
            "Triumph",
            "TVR",
            "Vauxhall",
            "Volkswagen",
            "Volvo",
            "Wiesmann",
            "W Motors",
            "Zenvo",
            "AC Cars",
            "Adler",
            "Aixam",
            "Alpina",
            "Alta",
            "AM General",
            "Ariel",
            "Artega",
            "Ascari",
            "Autobianchi",
            "Autovia",
            "BAC",
            "Barkas",
            "Beauford",
            "Bitter",
            "Borgward",
            "Brabus",
            "Bricklin",
            "Bristol",
            "Bufori",
            "BYD",
            "Cagiva",
            "Callaway",
            "Caterham",
            "Chang'an",
            "Chatenet",
            "Chery",
            "Chevrolet Corvette",
            "Chrysler Crossfire",
            "Cisitalia",
            "Cizeta",
            "Connaught",
            "Cord",
            "Covini",
            "Dacia",
            "Daewoo",
            "Daihatsu",
            "Daimler",
            "Datsun",
            "De Tomaso",
            "Delage",
            "Delahaye",
            "Denzel",
            "DeSoto",
            "Devon",
            "DKW",
            "Donkervoort",
            "Eagle",
            "Edsel",
            "Elfin",
            "Faraday Future",
            "FAW",
            "Fendt",
            "Fisker",
            "Frazer Nash",
            "GAZ",
            "Geo",
            "Ginetta",
            "Gumpert",
            "Haval",
            "Hennessey",
            "Hillman",
            "Hindustan",
            "Holden",
            "Hudson",
            "Humber",
            "IFA",
            "Imperial",
            "Innocenti",
            "Intermeccanica",
            "Invicta",
            "Isdera",
            "Iso",
            "Isotta Fraschini",
            "Italdesign",
            "Iveco",
            "Jannarelly",
            "Jensen",
            "Jowett",
            "Lorraine-Dietrich",
            "Luxgen",
            "Mahindra",
            "Marcos",
            "Maruti",
            "Maybach",
            "Mazda Autozam",
            "McLaren Senna",
        ];
        this.kleidung = [
            "Hemd",
            "Bluse",
            "T-Shirt",
            "Polohemd",
            "Hoodie",
            "Jacke",
            "Mantel",
            "Blazer",
            "Weste",
            "Pullover",
            "Strickjacke",
            "Tanktop",
            "Langarmshirt",
            "Sweatshirt",
            "Regenjacke",
            "Windbreaker",
            "Bomberjacke",
            "Anorak",
            "Parka",
            "Poncho",
            "Kimono",
            "Kleid",
            "Tunika",
            "Abendkleid",
            "Cocktailkleid",
            "Brautkleid",
            "Ballkleid",
            "Sommerkleid",
            "Maxikleid",
            "Minikleid",
            "Midikleid",
            "Skaterkleid",
            "Wickelkleid",
            "Etuikleid",
            "Shiftkleid",
            "Hemdblusenkleid",
            "Blusenkleid",
            "Jeans",
            "Shorts",
            "Bermudas",
            "Caprihose",
            "Stoffhose",
            "Anzugshose",
            "Chino",
            "Leggings",
            "Jeggings",
            "Cargo-Hose",
            "Jogginghose",
            "Trainingshose",
            "Sporthose",
            "Badeanzug",
            "Bikini",
            "Badehose",
            "Boardshorts",
            "Monokini",
            "Tankini",
            "Strickpullover",
            "Rollkragenpullover",
            "Fleecejacke",
            "Lederjacke",
            "Daunenjacke",
            "Steppjacke",
            "Regenmantel",
            "Trenchcoat",
            "Bolero",
            "Schal",
            "Halstuch",
            "Krawatte",
            "Fliege",
            "Handschuhe",
            "Mütze",
            "Kappe",
            "Hut",
            "Sonnenbrille",
            "Gürtel",
            "Hosenträger",
            "Socken",
            "Strumpfhose",
            "Legwarmers",
            "Stiefel",
            "Sportschuhe",
            "Sneakers",
            "Sandalen",
            "Flip-Flops",
            "Pumps",
            "High Heels",
            "Keilabsatz",
            "Plateauschuhe",
            "Ballerinas",
            "Loafers",
            "Bootsschuhe",
            "Espadrilles",
            "Wanderschuhe",
            "Arbeitsschuhe",
            "Sicherheitsschuhe",
            "Clogs",
            "Crocs",
            "Hausschuhe",
            "Regenstiefel",
        ];
        this.farbe = [
            "Altrosa",
            "Amaranth",
            "Amber",
            "Anthrazit",
            "Apfelgrün",
            "Apricot",
            "Aquamarin",
            "Aschgrau",
            "Azurblau",
            "Rot",
            "Blau",
            "Grün",
            "Gelb",
            "Orange",
            "Lila",
            "Pink",
            "Braun",
            "Grau",
            "Schwarz",
            "Weiß",
            "Beige",
            "Türkis",
            "Olivgrün",
            "Dunkelgrün",
            "Hellgrün",
            "Dunkelblau",
            "Hellblau",
            "Dunkelrot",
            "Hellrot",
            "Zitronengelb",
            "Limettengrün",
            "Lavendel",
            "Marineblau",
            "Kastanienbraun",
            "Mahagoni",
            "Gold",
            "Silber",
            "Kupfer",
            "Zinnoberrot",
            "Scharlachrot",
            "Babyblau",
            "Babyrosa",
            "Blassgrün",
            "Blassgelb",
            "Blasslila",
            "Blassorange",
            "Blassrot",
            "Bordeaux",
            "Dunkelgrau",
            "Hellgrau",
            "Karamell",
            "Kobaltblau",
            "Magenta",
            "Mokka",
            "Olivbraun",
            "Pfirsich",
            "Rubinrot",
            "Sand",
            "Schiefergrau",
            "Smaragdgrün",
            "Tannengrün",
            "Terrakotta",
            "Türkisblau",
            "Violett",
            "Ziegelrot",
            "Babygrün",
            "Babyviolett",
            "Dunkelbraun",
            "Dunkelviolett",
            "Eierschale",
            "Flieder",
            "Hellgelb",
            "Hellrosa",
            "Hellviolett",
            "Indigo",
            "Kirschrot",
            "Knallrot",
            "Lavendelblau",
            "Maigrün",
            "Olivgrau",
            "Pflaume",
            "Rauchblau",
            "Rostrot",
            "Salbeigrün",
            "Schwarzbraun",
            "Senfgelb",
            "Stahlblau",
            "Taupe",
            "Vanillegelb",
            "Waldgrün",
            "Weinrot",
            "Zartblau",
            "Zartgrün",
            "Zartorange",
            "Zartrosa",
            "Zartviolett",
            "Zimtbraun",
            "Azalee",
            "Blaugrau",
            "Blassrosa",
            "Bronze",
            "Dunkelgrasgrün",
            "Dunkelolivgrün",
            "Farngrün",
            "Heidekrautviolett",
        ];
        this.material = [
            "Baumwolle",
            "Wolle",
            "Leinen",
            "Seide",
            "Samt",
            "Leder",
            "Kunstleder",
            "Wildleder",
            "Denim",
            "Cord",
            "Polyester",
            "Viskose",
            "Acryl",
            "Polyamid",
            "Kaschmir",
            "Mohair",
            "Angora",
            "Alpaka",
            "Merinowolle",
            "Kaschmirwolle",
            "Kamelhaar",
            "Ziegenleder",
            "Schafleder",
            "Rindsleder",
            "Wildlederimitat",
            "Pelz",
            "Fell",
            "Fleece",
            "Spitze",
            "Organza",
            "Satin",
            "Brokat",
            "Chiffon",
            "Jersey",
            "Strickstoff",
            "Batikstoff",
            "Leopardenmuster",
            "Zebra-Muster",
            "Schlangenhautmuster",
            "Karomuster",
            "Streifenmuster",
            "Punkt-Muster",
            "Blumenmuster",
            "Paisleymuster",
            "Polka-Dot-Muster",
            "Hahnentritt-Muster",
            "Tweed",
            "Bouclé",
            "Jacquard",
            "WaffelpiquéKork",
            "Segeltuch",
            "Hanf",
            "Jute",
            "Canvas",
            "Veloursleder",
            "Mikrofaser",
            "Neopren",
            "Gore-Tex",
            "Softshell",
            "Ripstop",
            "Twill",
            "Popeline",
            "Chambray",
            "Voile",
            "Batist",
            "Taft",
            "Organischen Baumwolle",
            "Hanf-Baumwollmischung",
            "Leinen-Baumwollmischung",
            "Seiden-Baumwollmischung",
            "Jersey-Baumwollmischung",
            "Wolle-Leinen-Mischung",
            "Wolle-Seiden-Mischung",
            "Nylon",
            "Elasthan",
            "Spandex",
            "Gummi",
            "Latex",
            "Lurex",
            "Metallic-Stoff",
            "Plüsch",
            "Velours",
            "Lammfell",
            "Schaffell",
            "Mohair-Wolle-Mischung",
            "Leopardenfellimitat",
            "Zebraprint-Fellimitat",
            "Leopardenprint-Wildlederimitat",
            "Schlangenlederimitat",
            "Krokodillederimitat",
            "Straußenlederimitat",
            "Bambus",
            "Holz",
            "Keramik",
            "Laminat",
            "Vinyl",
            "Marmor",
            "Granit",
            "Glasfaser",
        ];
        this.verb = [
            "Abholen",
            "Absagen",
            "Abstimmen",
            "Anfangen",
            "Anhalten",
            "Ankommen",
            "Anmelden",
            "Anrufen",
            "Aufhören",
            "Aufmachen",
            "Aufstehen",
            "Ausfüllen",
            "Ausgehen",
            "Ausprobieren",
            "Aussteigen",
            "Backen",
            "Bauen",
            "Bedienen",
            "Bedienen",
            "Begrüßen",
            "Behalten",
            "Beobachten",
            "Beschreiben",
            "Besuchen",
            "Bewegen",
            "Bezahlen",
            "Bleiben",
            "Blockieren",
            "Blühen",
            "Brauchen",
            "Brennen",
            "Bringen",
            "Buchen",
            "Denken",
            "Diskutieren",
            "Drucken",
            "Einkaufen",
            "Einladen",
            "Einpacken",
            "Einschlafen",
            "Einsteigen",
            "Entdecken",
            "Entspannen",
            "Entscheiden",
            "Entwickeln",
            "Erklären",
            "Erreichen",
            "Essen",
            "Fahren",
            "Falten",
            "Feiern",
            "Fliegen",
            "Folgen",
            "Fotografieren",
            "Freuen",
            "Fühlen",
            "Gehen",
            "Gehören",
            "Gelten",
            "Genießen",
            "Gewinnen",
            "Grillen",
            "Haben",
            "Helfen",
            "Herstellen",
            "Hoffen",
            "Hören",
            "Informieren",
            "Interessieren",
            "Jagen",
            "Kaufen",
            "Kämpfen",
            "Klettern",
            "Kochen",
            "Kommen",
            "Konzentrieren",
            "Korrigieren",
            "Küssen",
            "Lächeln",
            "Laufen",
            "Leben",
            "Lernen",
            "Lieben",
            "Machen",
            "Mitbringen",
            "Mitkommen",
            "Mögen",
            "Nachdenken",
            "Öffnen",
            "Reisen",
            "Reservieren",
            "Schlafen",
            "Schreiben",
            "Schwimmen",
            "Sehen",
            "Spielen",
            "Sprechen",
            "Stehen",
            "Stören",
            "VerabschiedenVerändern",
            "Verbringen",
            "Vereinbaren",
            "Verkaufen",
            "Vermieten",
            "Verpassen",
            "Versuchen",
            "Verstehen",
            "Vertreten",
            "Verwenden",
            "Verzichten",
            "Vorbereiten",
            "Vorhaben",
            "Vorstellen",
            "Wählen",
            "Warten",
            "Waschen",
            "Wegwerfen",
            "Weinen",
            "Werben",
            "Werfen",
            "Wiederholen",
            "Wissen",
            "Wollen",
            "Wünschen",
            "Zählen",
            "Ziehen",
            "Zuhören",
            "Zuschauen",
            "Zuspätkommen",
            "Ablehnen",
            "Abschließen",
            "Ändern",
            "Anbieten",
            "Anfangen",
            "Anzeigen",
            "Auffordern",
            "Aufnehmen",
            "Aufpassen",
            "Ausschalten",
            "Aussprechen",
            "Austauschen",
            "Auswählen",
            "Befreien",
            "Befürchten",
            "Begegnen",
            "Begleiten",
            "Begründen",
            "Behandeln",
            "Beilegen",
            "Beispiele geben",
            "Bekanntmachen",
            "Benutzen",
            "Beraten",
            "Berichten",
            "Beschränken",
            "Beschweren",
            "Bestehen",
            "Bewerben",
            "Bewirken",
            "Bleiben",
            "Dauern",
            "Dienen",
            "Duschen",
            "Eignen",
            "Entfernen",
            "Entschuldigen",
            "Entspannen",
            "Enttäuschen",
            "Entwickeln",
            "Erfinden",
            "Erhalten",
            "Erkennen",
            "Erleben",
            "Erlernen",
            "Ersetzen",
            "Erwarten",
            "Erzählen",
            "Fassen",
            "Festlegen",
            "Festnehmen",
            "Finden",
            "Flüstern",
            "Fordern",
            "Fotografieren",
            "Freigeben",
            "Freuen",
            "Gelingen",
            "Gehorchen",
            "Gelten",
            "Genießen",
            "Geraten",
            "Geschickt sein",
            "Gewinnen",
            "Glauben",
            "Helfen",
            "Herstellen",
            "Hoffen",
            "Informieren",
            "Interessieren",
        ];
        this.sportArt = [
            "American Football",
            "Baseball",
            "Basketball",
            "Boxen",
            "Cricket",
            "Eislaufen",
            "Eiskunstlauf",
            "Eisschnelllauf",
            "Fechten",
            "Feldhockey",
            "Fußball",
            "Golf",
            "Handball",
            "Inline-Skaten",
            "Judo",
            "Kanu",
            "Karate",
            "Kegeln",
            "Klettern",
            "Kugelstoßen",
            "Langlauf",
            "Leichtathletik",
            "Mountainbiking",
            "Nordic Walking",
            "Paintball",
            "Pferderennen",
            "Polo",
            "Racquetball",
            "Rennradfahren",
            "Rudern",
            "Rugby",
            "Schach",
            "Schwimmen",
            "Skateboarden",
            "Skifahren",
            "Snowboarden",
            "Squash",
            "Surfen",
            "Taekwondo",
            "Tischtennis",
            "Triathlon",
            "Volleyball",
            "Wakeboarding",
            "Wasserball",
            "Wasserski",
            "Windsurfen",
            "Wrestling",
            "Yoga",
            "Badminton",
            "Bogenschießen",
            "Bowling",
            "Bridge",
            "Curling",
            "Darts",
            "Drachenbootfahren",
            "Fallschirmspringen",
            "Federball",
            "Fischen",
            "Flag Football",
            "Freeskiing",
            "Freestyle-Skifahren",
            "Gleitschirmfliegen",
            "Handbike",
            "Kajakfahren",
            "Kitesurfen",
            "Marathon",
            "Mountainboarding",
            "Nordic Combined",
            "Paragliding",
            "Pistolenschießen",
            "Quadfahren",
            "Rafting",
            "Ringen",
            "Rollstuhlbasketball",
            "Rollstuhltennis",
            "Rugby League",
            "Rugby Union",
            "Schießen",
            "Schnorcheln",
            "Segeln",
            "Skatecross",
            "Skibergsteigen",
            "Skilanglauf-Biathlon",
            "Skispringen",
            "Speedskating",
            "Stand-Up-Paddling",
            "Streetball",
            "Synchroschwimmen",
            "Tanzsport",
            "Teamgym",
            "Tennis",
            "Trampolinspringen",
            "Ultimate Frisbee",
            "Volleyballbeach",
            "Wassergymnastik",
            "Wasserpolo",
            "Wing Tsun",
            "ZumbaAikido",
            "Apnoetauchen",
            "Aquabike",
            "Aquajogging",
            "Ballett",
            "Bodybuilding",
            "Bouldern",
            "Capoeira",
            "Cheerleading",
            "Crossfit",
            "Cyclocross",
            "Dartpfeilwerfen",
            "Eisangeln",
            "Fahrradpolo",
            "Feldfaustball",
            "Finswimming",
            "Flagfootball",
            "Fliegenfischen",
            "Footbag",
            "Freestyle-Fußball",
            "Freestyle-Skateboarding",
            "Gehen",
            "Gymnastik",
            "Hacky Sack",
            "Hanggliding",
            "Heißluftballonfahren",
            "Hürdenlauf",
            "Indiaca",
            "Jai Alai",
            "Jiu-Jitsu",
            "Jogging",
            "Kanupolo",
            "Kendo",
            "Langhanteltraining",
            "Le Parkour",
            "Luftgewehrschießen",
            "Marathonlauf",
            "Minigolf",
            "Mountainbike-Triathlon",
            "Nordic Fitness",
            "Orientierungslauf",
            "Padelsport",
            "Parkour",
            "Parkour/Freerunning",
            "Pétanque",
            "Pilates",
            "Powerlifting",
            "Qigong",
            "Radball",
            "Radpolo",
            "Radsport",
            "Reiten",
            "Rhythmisches Sportgymnastik",
            "Riesenslalom",
            "Rock Climbing",
            "Rope Skipping",
            "Rundstreckenrennen",
            "Salsa",
            "Schachboxen",
            "Schneeschuhwandern",
            "Schwertkampf",
            "Segelfliegen",
            "Selbstverteidigung",
            "Skijöring",
            "Slamball",
            "Snooker",
            "Snowbiking",
            "Snowkiting",
            "Snowshoeing",
            "Softball",
            "Spinning",
            "Street Workout",
            "Tanzen",
            "Tischfußball",
            "Tourenski",
            "Trailrunning",
            "Trampolinturnen",
            "Turnen",
            "Unterwasserhockey",
            "Wing Chun",
        ];
    }

    suche(array, letter) {
        const gefundeneElemente = array.filter((element) =>
            element[0].toLowerCase().startsWith(letter.toLowerCase())
        );
        return gefundeneElemente[
            Math.floor(Math.random() * gefundeneElemente.length)
        ];
    }

    startWith(b) {
        const stadtBuch = this.suche(this.stadt, b);
        const länderBuch = this.suche(this.länder2, b);
        const flussBuch = this.suche(this.flusse, b);
        const namenBuch = this.suche(this.namen, b);
        const hausHaltsBuch = this.suche(this.hausHalts, b);
        const pflanzeBuch = this.suche(this.pflanze, b);
        const tierBuch = this.suche(this.tier, b);
        const berufBuch = this.suche(this.beruf, b);
        const autosBuch = this.suche(this.autos, b);
        const kleidungBuch = this.suche(this.kleidung, b);
        const farbeBuch = this.suche(this.farbe, b);
        const materialBuch = this.suche(this.material, b);
        const verbBuch = this.suche(this.verb, b);
        const sportArtBuch = this.suche(this.sportArt, b);
        return (
            chalk.red("Stadt :") +
            stadtBuch +
            " " +
            chalk.red("Land:") +
            länderBuch +
            " " +
            chalk.red("Fluss:") +
            flussBuch +
            " " +
            chalk.red("Name:") +
            namenBuch +
            " " +
            chalk.red("HausHalts:") +
            hausHaltsBuch +
            " " +
            chalk.red("Pflanze:") +
            pflanzeBuch +
            " " +
            chalk.red("Tier:") +
            tierBuch +
            " " +
            chalk.red("Beruf:") +
            berufBuch +
            " " +
            chalk.red("Auto:") +
            autosBuch +
            " " +
            chalk.red("Kleidung:") +
            kleidungBuch +
            " " +
            chalk.red("Farbe:") +
            farbeBuch +
            " " +
            chalk.red("Material:") +
            materialBuch +
            " " +
            chalk.red("Verb:") +
            verbBuch +
            " " +
            chalk.red("SportArt:") +
            sportArtBuch
        );
    }
}

const chalk = require("chalk");
const prompt = require("prompt-sync")();
// //
// // get input from the user.
// //
const start = new spiele();
const b = prompt("Bitte gib einen Buchstaben ein: ");


console.log(start.startWith(b));