let flüsse = [
    "Amazonas",
    "Xar Moron  ",
    "Xiliao He",
    "Nil",
    "Yangtze",
    "Mississippi",
    "Danube",
    "Yenisei",
    "Yellow River",
    "Congo",
    "Paraná",
    "Indus",
    "Ganges",
    "Murray",
    "Volga",
    "Rhine",
    "Mekong",
    "Colorado",
    "Qiantang",
    "Orinoco",
    "Tigris",
    "Amazonas",
    "Brahmaputra",
    "Hudson",
    "Thames",
    "Jordan",
    "St.Lawrence",
    "Yarra",
    "Irrawaddy",
    "Rhein",
    "Seine",
    "Donau",
    "Ob",
    "Rhône",
    "Ebro",
    "Po",
    "Elbe",
    "Tiber",
    "Douro",
    "Loire",
    "Dnjepr",
    "Lena",
    "Ural",
    "Isère",
    "Savannah",
    "Sacramento",
    "Euphrat",
    "Shatt",
    "Brahmaputra",
    "Niger",
    "Zambezi",
    "Amur",
    "Columbia",
    "Huai",
    "Rio_Grande",
    "Yellowstone",
    "Rio de la Plata",
    "Murray-Darling",
    "Yangtze",
    "Mackenzie",
    "Niger",
    "Missouri",
    "Vistula",
    "São Francisco",
    "Rio Paraná",
    "Arno",
    "Syr Darya(",
    "Danube",
    "Indigirka(Russland)",
    "Rio de Janeiro",
    "Thames",
    "Rhone",
    "Rio Negro",
    "Kolyma",
    "Rio Formoso",
    "Rio Sucuri",
    "Rio Xingu",
    "Rio Araguaia",
    "Rio Tocantins",
    "Rio Madeira",
    "Rio São Francisco",
    "Rio Paraná",
    "Rio Colorado",
    "Rio Paraná Guazú",
    "Rio Uruguay",
    "Rio Pilcomayo",
    "Rio Bermejo",
    "Rio Colorado",
    "Rio Baker",
    "Rio Loa",
    "Rio Maipo",
    "Rio Claro",
    "Rio Limari",
    "Rio Aconcagua",
    "Rio Mapocho",
    "Rio Tolten",
    "Rio Itata",
    "Rio Biobío",
    "Rio Imperial",
    "Rio Cruces",
    "Rio Valdivia",
    "Rio Nuble",
    "Rio Laja",
    "Rio Yali",
    "Rio Choapa",
    "Rio Petorca",
    "Rio Quillota",
    "Rio Cachapoal",
    "Rio Rapel",
    "Rio Mataquito",
    "Rio Teno",
    "Rio Claro",
    "Rio Huallaga",
    "Rio Ucayali",
    "Rio Marañon",
    "Rio Amazonas",
    "Rio Napo",
    "Rio Putumayo",
    "Rio Orinoco",
    "Rio Magdalena",
    "Rio Caquetá",
    "Rio Atrato",
    "Rio Patía",
    "Rio Cauca",
    "Rio Sinú",
    "Rio Quito",
    "Rio Guayas",
    "Rio Pastaza",
    "Rio Napo",
    "Rio Coca",
    "Rio Amazonas",
    "Rio Ucayali",
    "Rio Paraná",
    "Rio de la Plata",
    "Rio Paraná",
    "Rio Paraguay",
    "Rio Pilcomayo",
    "Rio Bermejo",
    "Rio Paraguay",
    "Rio Apa",
    "Rio Iguaçu",
    "Rio Madeira",
    "Rio Xingu",
    "Rio Tocantins",
    "Rio Araguaia",
    "Rio São Francisco",
    "Rio Doce",
    "Rio Parnaíba",
    "Rio Jacuí",
    "Rio Grande",
    "Rio Negro",
    "Rio Amazonas",
    "Rio Solimões",
    "Rio Juruá",
    "Rio Purus",
    "Rio Madeira",
    "Rio Xingu",
    "Rio Tocantins",
    "Rio Araguaia",
    "Rio São_Francisco",
    "Rio Itajaí",
    "Rio Tibagi",
    "Rio Iguaçu",
    "Rio Paraná",
    "Riode la Plata)",
    "Rio Colorado",
    "Rio Grande",
    "Rio Missouri",
    "Rio Columbia",
    "Rio Snake",
    "Rio Mississippi",
    "Rio Ohio",
    "Rio Cumberland",
    "Rio Tennessee",
    "Rio Yazoo",
    "Rio Red",
    "Rio Arkansas",
    "Rio Trinity",
    "Rio Brazos",
    "Rio Guadalupe",
    "Rio Rio Grande",
    "Rio Pecos",
    "Rio Yukon",
    "Rio Mackenzie",
    "Rio St.Lawrence",
    "Rio Nelson",
    "Rio Fraser",
    "Rio Columbia",
    "Rio Skeena",
    "Rio Athabasca",
    "Rio Peace",
    "Rio Churchill",
    "Rio Liard",
    "Rio Coppermine",
    "Rio Hayes",
    "Rio Rideau",
    "Rio Ottawa",
    "Rio St.John",
    "Thames",
    "Severn",
    "Trent",
    "Tyne",
    "Dee",
    "Clyde",
    "Avon",
    "Mersey",
    "Humber",
    "Tees",
    "Forth",
    "Tweed",
    "Tamar",
    "Exe",
    "Ouse ",
    "Wear ",
    "Rhine",
];

let namen = [
    "Emma",
    "Mia",
    "Sophia",
    "Olivia",
    "Isabella",
    "Ava",
    "Lily",
    "Zoe",
    "Charlotte",
    "Amelia",
    "Harper",
    "Evelyn",
    "Abigail",
    "Aria",
    "Aaliyah",
    "Scarlett",
    "Riley",
    "Paul",
    "Ella",
    "Mia",
    "Peter",
    "Philipp",
    "Patricia",
    "Pamela",
    "Penelope",
    "Patrick",
    "Paige",
    "Percy",
    "Xavier",
    "Xander",
    "Ximena",
    "Xiomara",
    "Xaver",
    "Priscilla",
    "Addison",
    "Elizabeth",
    "Sofia",
    "Avery",
    "Elliana",
    "Scarlett",
    "Grace",
    "Victoria",
    "Madison",
    "Chloe",
    "Penelope",
    "Layla",
    "Rylee",
    "Aubrey",
    "Harper",
    "Evelyn",
    "Adalynn",
    "Adalyn",
    "Hazel",
    "Nora",
    "Lily",
    "Willa",
    "Luna",
    "Kennedy",
    "Mackenzie",
    "Sadie",
    "Peyton",
    "Ellie",
    "Nova",
    "Leah",
    "Audrey",
    "Skylar",
    "Naomi",
    "Camila",
    "Anna",
    "Avery",
    "Ariana",
    "Allison",
    "Caroline",
    "Genesis",
    "Madelyn",
    "Adeline",
    "Maya",
    "Scarlett",
    "Ellie",
    "Aubree",
    "Aria",
    "Kaylee",
    "Avery",
    "Sarah",
    "Natalie",
    "Addison",
    "Hazel",
    "Brooklyn",
    "Zoey",
    "Elaina",
    "Brianna",
    " Jasmine",
    "Westlynn",
    "Autumn",
    "Adalyn",
    "Mariah",
    "Ruby",
    "Caroline",
    "Ellis",
    "Mila",
    "Finley",
    "Kennedi",
    "Skylar",
    "Harper",
    "Adalynn",
    "Annabelle",
    "Paisley",
    "Presley",
    "Michaela",
    " Eloise",
    "Rowan",
    "Josephine",
    "Delilah",
    "Julianna",
    "Alaina ",
    "Sophia",
    "Mia",
    "Isabella",
    "Olivia",
    "Ava",
    "Lily",
    "Zoe",
    "Charlotte",
    "Amelia",
    "Una",
    "Quentin",
    "Quinn",
    "Quirin",
    "Quirina",
    "Quirinus",
    "Quoc",
    "Qiana",
    "Qadir",
    "Qasim",
    "Qiana",
    "Uriel",
    "Uliana",
    "Ugo",
    "Ulises",
    "Upton",
    "Uzair",
    "Umair",
    "Unaiza",
    "Umar",
    "Ursula",
    "Udo",
    "Ulrich",
    "Ulla",
    "Ute",
    "Ulrike",
    "Ulf",
    "Uwe",
    "Uschi",
    "Urban",
    "Harper",
    "Evelyn",
    "Abigail",
    "Scarlett",
    "Aria",
    "Aaliyah",
    "Riley",
    "Ella",
    "Addison",
    "Elizabeth",
    "Sofia",
    "Avery",
    "Elliana",
    "Madison",
    "Chloe",
    "Penelope",
    "Layla",
    " Rylee",
    "Aubrey",
    "Nora",
    "Lily",
    "Willa",
    "Luna",
    "Kennedy",
    "Mackenzie",
    "Sadie",
    "Peyton",
    "Ellie",
    "Nova",
    "Leah",
    "Audrey",
    "Skylar",
    "Naomi",
    "Camila",
    "Anna",
    "Ariana",
    "Allison",
    "Caroline",
    "Genesis",
    "Madelyn",
    "Adeline",
    "Maya",
    "Ellis",
    "Mila",
    "Finley",
    "Kennedi",
    "Brianna",
    "Jasmine ",
    "Westlynn",
    "Autumn",
    "Mariah",
    "Ruby",
    "Eloise",
    "Rowan",
    "Josephine",
    "Delilah",
    "Julianna",
    "Alaina",
    "Emma",
    "Harper",
    "Adalynn ",
    "Paisley ",
    "Presley ",
    "Michaela",
    "Elaina",
    "Zoey",
    "Autumn",
    "Adalyn",
    " Sarah",
    "Grace",
    "Victoria",
    "Isabelle",
    "Harper",
    "Adeline",
    "Lillian",
    "Lulu",
    "Freya",
    "Harper",
    "Amelia",
    "Harper",
    "Elsie",
    "Caroline",
    "Eleanor",
    "Aurora",
    "Harper",
    "Alexander",
    "William",
    "Benjamin",
    "Henry",
    "Samuel",
    "Oliver",
    "George",
    "Felix",
    "Liam",
    "Maximilian",
    "Jasper",
    "Owen",
    "Louis",
    "Victor",
    "Leo",
    "Caleb",
    "Oscar",
    "Felix",
    "Felix (Latein)",
    "Benjamin ",
    "Ethan ",
    "James",
    "Joseph",
    "Matthew",
    "Daniel",
    "Andrew",
    "David",
    "Christopher",
    "Nathan",
    "Jack",
    "Nicholas",
    "Tyler",
    "Ryan",
    "Adam",
    "Jonathan",
    "Zachary",
    "Justin",
    "Alexander",
    "Thomas",
    "Caleb",
    "Evan",
    "Luke",
    "Mason",
    "Gabriel",
    "Isaac",
    "Michael",
    "Dylan",
    "Joshua",
    "Christian",
    "Elijah",
    "Aaron",
    "Connor",
    "Juan",
    "Nathan",
    "Samuel",
    "Adrian",
    "Travis",
    "Caleb",
    "Jordan",
    "Henry",
    "Jack",
    "Caleb",
    "Dylan",
    "Owen",
    "Kyle",
    "Caleb",
    "Nathan",
    "Landon",
    "Tyler",
    "Austin",
    "Isaac",
    "Evan",
    "Nathan",
    "Adam",
    "Aaron",
    "Jared",
    "Alexander",
    "Brandon",
    "Jason",
    "Jared",
    "Andrew",
    "Ethan",
    "Luke",
    "Benjamin",
    "Noah",
    "Joshua",
    "Caleb",
    "Jacob",
    "Ethan",
    "William",
    "Michael",
    "Christopher",
    "Nicholas",
    "Matthew",
    "Joshua",
    "Daniel",
    "James",
    "Alexander",
    "John",
    "Andrew",
    "Joseph",
    "David",
    "Ryan",
    "Thomas",
    "Adam",
    "Zachary",
    "Robert",
    "Kevin",
    "Jason",
    "Benjamin",
    "Charles",
    "Jonathan",
    "Justin",
    "Nathan",
    "Tyler",
    "Gabriel",
    "Ethan",
    "Jacob",
    "Mark",
    "Samuel",
    "Christian",
    "Brandon",
    "Aaron",
    "Richard",
    "Alexander",
    "Brian",
    "Christopher",
    "Ryan",
    "David",
    "William",
    "Joshua",
    "Christopher",
    "Nathan",
    "Adam",
    "Michael",
    "Matthew",
    "Brian ",
    "Thomas)",
    "James",
    "Youssef",
    "Yvonne",
    "Yasmin",
    "Yves",
    "Yannick",
    "Yara",
    "Yannis",
    "Yael",
    "Yvette",
    "Yale",
    "Yuri",
];
let haussHallt = [
    "Abfalleimer",
    "Akkuschrauber",
    "Apfelentkerner",
    "Armlehnstuhl",
    "Aschenbecher",
    "Aufbewahrungsbox",
    "Auflaufform",
    " Ausstechform",
    "Teller",
    "Schüsseln",
    "Tassen",
    "Gläser",
    "Besteck",
    "Messer",
    "Gabeln",
    "Löffel",
    "Kochlöffel",
    "Pfannenwender",
    "Pfannen",
    "Töpfe",
    "Bräter",
    "Backbleche",
    "Schneidebretter",
    "Scheren",
    "Schäler",
    "Kartoffelstampfer",
    "Spülbürste",
    "Staubsauger",
    "Besen",
    "Handfeger",
    "Wischmop",
    "Putzeimer",
    "Putzlappen",
    "Reinigungsspray",
    "Geschirrspülmittel",
    "Waschmaschine",
    "Trockner",
    "Bügeleisen",
    "Bügelbrett",
    "Kleiderbügel",
    "Bettwäsche",
    "Handtücher",
    "Kissen",
    "Decken",
    "Lampen",
    "Steckdosen",
    "Verlängerungskabel",
    "Elektrorasierer",
    "Haartrockner",
    "Glätteisen",
    "Lockenstab",
    "Zahnbürste",
    "Zahnpasta",
    "Seife",
    "Shampoo",
    "Conditioner",
    "Duschgel",
    "Handseife",
    "Toilettenpapier",
    "Taschentücher",
    "Papierhandtücher",
    "Müllbeutel",
    "Mülleimer",
    "Schaufel",
    "Besen",
    "Schrubber",
    "Gartenschlauch",
    "Gartenschere",
    "Rasenmäher",
    "Laubbläser",
    "Fahrrad",
    "Rollschuhe",
    "Skateboard",
    "Inline-Skates",
    "Tisch",
    "Stühle",
    "Sofa",
    "Sessel",
    "Regale",
    "Betten",
    "Schränke",
    "Kommode",
    "Fernseher",
    "Computer",
    "Tastatur",
    "Maus",
    "Drucker",
    "Scanner",
    "Kaffeemaschine",
    "Toaster",
    "Wasserkocher",
    "Mikrowelle",
    "Backofen",
    "Herd",
    "Kühlschrank",
    "Gefrierschrank",
    "Geschirrspüler",
    "Nähmaschine",
    "Bücherregal",
    "Vasen",
    "Kerzenhalter",
    "Spiegel",
    "Gardinen",
    "Teppiche",
    "Lampenschirme",
    "Teelichter",
    "Gartenmöbel",
    "Briefkasten",
];
let tiere = [
    "",
    "Pottwal",
    "Xenopus",
    "Orcinus_orca_(Schwertwal)",
    "Großer_Tümmler",
    "Weißseitendelfin",
    "Gemeiner_Delfin",
    "Buckelwal",
    "Finnwal",
    "Brydewal",
    "Seiwal",
    "Blauwal",
    "Schweinswal",
    "Utah-Klippschliefer",
    "Umbrellavogel",
    "Usambaraveilchenaffe",
    "Ussurischer Tiger",
    "Uhuwachtel",
    "Uromastyx (Wüstendornschwanz)",
    "Utahraptor",
    "Ussurikatze",
    "Ufermaus",
    "Unterirdischer Hundsfisch",
    "Irrawaddy-Delfin",
    "Indischer Flussdelphin",
    "Ganges-Delfin",
    "Vaquita",
    "Gewöhnlicher Schweinswal",
    "Rundkopfdelfin",
    "Kurzflossen-Grindwal",
    "Langflossen-Grindwal",
    "Streifendelfin",
    "Rauzahndelfin",
    "Zwergwal",
    "Hector-Delfin",
    "Kleiner Schwertwal",
    "Indopazifischer Großer Tümmler",
    "Dusky-Delfin",
    "Glattwal",
    "Beluga",
    "Grauwal",
    "Nordkaper",
    "Südkaper",
    "Pudú-Delfin",
    "Risso-Delfin",
    "Baird-Beaked-Wal",
    "Uhu",
    "Urang-Utan",
    "Uakari",
    "Uferläufer",
    "Uferschnepfe",
    "Uhu",
    "Unke",
    "Urial",
    "Urraca",
    "Unterwasserfliege",
    "Tucuxi",
    "Weißflanken-Delfin",
    "Atlantischer Delfin",
    "Dall-Delfin",
    "Chile-Delfin",
    "Commerson-Delfin",
    "Amazonas-Delfin",
    "Indischer Ozean Grindwal",
    "Fraser-Delfin",
    "Geomys-Delfin",
    "Schwarzdelfin",
    "Südlicher Glattwal",
    "Tümmler der Nordostküste von Schottland",
    "Langschwanzdelfin",
    "Hourglass-Delfin",
    "Atlantic Humpback Dolphin",
    "Indischer Ozean Delfin",
    "Delfin von Guadalupe",
    "Atlantik-Grauflossen-Delfin",
    "Blau-Weiße-Delfin",
    "Northern Right Whale Dolphin",
    "Zügeldelfin",
    "Spitzkopfdelfin",
    "Borneo-Delfin",
    "Spinner-Delfin",
    "Clymene-Delfin",
    "Burmeister-Delfin",
    "Schwarzschnauzen-Delfin",
    "La-Plata-Delfin",
    "Gervais-Delfin",
    "Peale's Dolphin",
    "Atlantic Spotted Dolphin",
    "Fraser's Dolphin",
    "Gray's Spinner Dolphin",
    "Heaviside's Dolphin",
    "Hector's Beaked Whale",
    "Melon-Headed Whale",
    "Northern Bottlenose Whale",
    "Pacific White-Sided Dolphin",
    "Pantropical Spotted Dolphin",
    "Pygmy Killer Whale",
    "Pygmy Sperm Whale",
    "Risso's Dolphin",
    "Rough-Toothed Dolphin",
    "Short-Beaked Common Dolphin",
    "Southern Bottlenose Whale",
    "Southern Hemisphere Humpback Dolphin",
    "Southern Right Whale Dolphin",
    "Spectacled Porpoise",
    "Spotted Dolphin",
    "Striped Dolphin",
    "Fraser's Dolphin",
    "Ganges River Dolphin",
    "Dusky Dolphin",
    "Atlantic Humpback Dolphin",
    "Indo-Pacific Humpback Dolphin",
    "Long-Finned Pilot",
    "Gemeine Großohrfledermaus",
    "Langflügelfledermaus",
    "Wasserfledermaus",
    "Breitflügelfledermaus",
    "Mopsfledermaus",
    "Bartfledermaus",
    "Graue Langzungenfledermaus",
    "Kleine Hufeisennase",
    "Abendsegler",
    "Fransenlippenfledermaus",
    "Kleiner Abendsegler",
    "Zweifarbfledermaus",
    "Breitflügel-Fruchtvampir",
    "Rotflügel-Fruchtvampir",
    "Flughund",
    "Kahle Fledermaus",
    "Saddleback Fledermaus",
    "Big Brown Fledermaus",
    "Gelbe Fledermaus",
    "Braune Fledermaus",
    "Myotis Lucifugus",
    "Große Abendsegler",
    "Mückenschreck",
    "Riesengleithörnchen",
    "Zwergflughund",
    "Spitzenflügelfledermaus",
    "Kurzschnauzenflughund",
    "Falsche Vampirfledermaus",
    "Nacktschwanz-Rundblattnase",
    "Gould-Fruchttaube",
    "Blassgesicht-Blütenfledermaus",
    "Borneo-Pustelfledermaus",
    "Seba's Kurzohrfledermaus",
    "Jamaicaner Fledermaus",
    "Korsischer Hufeisennase",
    "Felsenkänguru",
    "Pallid Fledermaus",
    "Silberfledermaus",
    "Langnasen-Fruchtvampir",
    "Größerer Knochenflügelfledermaus",
    "Weißrückengleithörnchen",
    "Nördliche Fledermaus",
    "Thailändische Rundblattnase",
    "Große Rundblattnase",
    "Brandts Fledermaus",
    "Waldmurmeltier",
    "Wiesenfledermaus",
    "Diademflughund",
    "Ockerflügelfledermaus",
    "Atlantische Flughund",
    "Nordamerikanischer Flussotter",
    "Rosafarbene Spitzmausfledermaus",
    "Rote Fledermaus",
    "Große Braune Fledermaus",
    "Chinesischer Glattnasenfledermaus",
    "Kastanienbraune Fledermaus",
    "Sri-Lanka-Fruchttaube",
    "Rotrückenfruchttaube",
    "Nördlicher Wollaffe",
    "Yuma Myotis",
    "Graue Großohrfledermaus",
    "Langnasen-Blütenfledermaus",
    "Gewöhnlicher Kinnblattnasenfledermaus",
    "Großohriges Känguru",
    "Schwarzflügel-Fruchtvampir",
    "Jamaikanische Fruchtvampirfledermaus",
    "Gemeine Großohrfledermaus",
    "Langflügelfledermaus",
    "Wasserfledermaus",
    "Breitflügelfledermaus",
    "Mopsfledermaus",
    "Bartfledermaus",
    "Graue Langzungenfledermaus",
    "Kleine Hufeisennase",
    "Abendsegler",
    "Fransenlippenfledermaus",
    "Kleiner Abendsegler",
    "Zweifarbfledermaus",
    "Breitflügel-Fruchtvampir",
    "Rotflügel-Fruchtvampir",
    "Flughund",
    "Kahle Fledermaus",
    "Saddleback Fledermaus",
    "Big Brown Fledermaus",
    "Gelbe Fledermaus",
    "Braune Fledermaus",
    "Myotis Lucifugus",
    "Große Abendsegler",
    "Mückenschreck",
    "Riesengleithörnchen",
    "Zwergflughund",
    "Spitzenflügelfledermaus",
    "Kurzschnauzenflughund",
    "Falsche Vampirfledermaus",
    "Nacktschwanz-Rundblattnase",
    "Gould-Fruchttaube",
    "Blassgesicht-Blütenfledermaus",
    "Borneo-Pustelfledermaus",
    "Seba's Kurzohrfledermaus",
    "Jamaicaner Fledermaus",
    "Korsischer Hufeisennase",
    "Felsenkänguru",
    "Pallid Fledermaus",
    "Silberfledermaus",
    "Langnasen-Fruchtvampir",
    "Größerer Knochenflügelfledermaus",
    "Weißrückengleithörnchen",
    "Nördliche Fledermaus",
    "Thailändische Rundblattnase",
    "Große Rundblattnase",
    "Brandts Fledermaus",
    "Waldmurmeltier",
    "Wiesenfledermaus",
    "Diademflughund",
    "Ockerflügelfledermaus",
    "Atlantische Flughund",
    "Nordamerikanischer Flussotter",
    "Rosafarbene Spitzmausfledermaus",
    "Rote Fledermaus",
    "Große Braune Fledermaus",
    "Chinesischer Glattnasenfledermaus",
    "Kastanienbraune Fledermaus",
    "Sri-Lanka-Fruchttaube",
    "Rotrückenfruchttaube",
    "Nördlicher Wollaffe",
    "Yuma Myotis",
    "Graue Großohrfledermaus",
    "Langnasen-Blütenfledermaus",
    "Gewöhnlicher Kinnblattnasenfledermaus",
    "Großohriges Känguru",
    "Schwarzflügel-Fruchtvampir",
    "Jamaikanische Fruchtvampirfledermaus",
    "Bienen",
    "Wespen",
    "Schmetterlinge",
    "Raupen",
    "Käfer",
    "Grashüpfer",
    "Heuschrecken",
    "Schaben",
    "Spinnen",
    "Skorpione",
    "Tausendfüßer",
    "Kakerlaken",
    "Termiten",
    "Libellen",
    "Asseln",
    "Fliegen",
    "Stechmücken",
    "Zecken",
    "Blattläuse",
    "Marienkäfer",
    "Ohrwürmer",
    "Schmetterlingsraupen",
    "Silberfische",
    "Springschwänze",
    "Zebraspinnen",
    "Riesenvogelspinnen",
    "Dornfinger",
    "Kraken",
    "Garnelen",
    "Krebse",
    "Seesterne",
    "Seeigel",
    "Schnecken",
    "Muscheln",
    "Tintenfische",
    "Quallen",
    "Anemonen",
    "Korallen",
    "Schwämme",
    "Seepferdchen",
    "Tintenfischseiche",
    "Hummer",
    "Langusten",
    "Krabben",
    "Tintenfischartige",
    "Schlangensterne",
    "Flamingoseidechsen",
    "Chamäleons",
    "Skorpionspinnen",
    "Seeanemonen",
    "Meeresschlangen",
    "Seeschlangen",
    "Gottesanbeterinnen",
    "Blattschneiderameisen",
    "Falterfische",
    "Rotfeuerfische",
    "Drachenköpfe",
    "Barrakudas",
    "Seepferdchen",
    "Seeohren",
    "Einsiedlerkrebse",
    "Teufelskrabben",
    "Seepocken",
    "Krustentiere",
    "Eidechsen",
    "Nacktschnecken",
    "Kreuzspinnen",
    "Trichterspinnen",
    "Hausmäuse",
    "Feldmäuse",
    "Wasserflöhe",
    "Seeanemonen",
    "Schwertlilien",
    "Regenwürmer",
    "Flusskrebse",
    "Flusspferdkrabben",
    "Schlammspringer",
    "Schlammschnecken",
    "Dornenkronenseesterne",
    "Kröten",
    "Frösche",
    "Seefüchse",
    "Seeigel",
    "Seepferdchen",
    "Feuerwanzen",
    "Schildläuse",
    "Laufkäfer",
    "Eintagsfliegen",
    "Schnaken",
    "Mückenlarven",
    "Springspinnen",
    "Milben",
    "Springschwänze",
    "Asselkrebse",
    "Assel",
    "Landkrabben",
    "Langschwanzmakaken",
    "Kaiserkrabben",
    "Riesenassel",
    "Känguru",
    "Wallaby",
    "Koala",
    "Wombat",
    "Tasmanischer Teufel",
    "Opossum",
    "Beutelratte",
    "Bilchbeutler",
    "Kletterbeutler",
    "Ringelschwanz-Filander",
    "Fadenschwanzbeutler",
    "Flughund",
    "Kurzschnabeligel",
    "Langschnabeligel",
    "Schnabeligel",
    "Zwergbeutelmarder",
    "Schnabeltier",
    "Nasenbeutler",
    "Bergkänguru",
    "Buschkänguru",
    "Gelbfuß-Felskänguru",
    "Roter Riesenkänguru",
    "Schwarznasenkänguru",
    "Baumkänguru",
    "Graukänguru",
    "Riesengleitbeutler",
    "Brauner Gleitbeutler",
    "Zuckertütenbaumkänguru",
    "Rotes Rattenkänguru",
    "Tasmanischer Fuchs",
    "Neuguinea-Kurzkopfbeutler",
    "Ameisenbeutler",
    "Haarschwanz-Rattenkänguru",
    "Spitzkopf-Felsenkänguru",
    "Mahagonibaumkänguru",
    "Östlicher Grauer Riesenkänguru",
    "Krokodilschwanzskink",
    "Krokodilwaran",
    "Grünleguan",
    "Kragenechse",
    "Krokodilkopfgecko",
    "Waran",
    "Leguan",
    "Gila-Krustenechse",
    "Halsbandleguan",
    "Grünschwanzleguan",
    "Pantherchamäleon",
    "Köhlerschildkröte",
    "Karettschildkröte",
    "Lederschildkröte",
    "Grüne Meeresschildkröte",
    "Schwarze Königsnatter",
    "Königskobra",
    "Krokodilschwanzskink",
    "Teppichpython",
    "Grüner Leguan",
    "Sumpfschildkröte",
    "Wüstenschildkröte",
    "Südlicher Höckerschildkröte",
    "Australischer Pythong",
    "Pazifischer Lederschildkröte",
    "Riesenschildkröte",
    "Mangrovenpython",
    "Gelbkopfschildkröte",
    "Echte Geckos",
    "Neuguinea-Waldkänguru",
    "Beutelwolf",
    "Bandikut",
    "Tüpfelbeutelmarder",
    "Südamerikanischer Opossum",
    "Numbat",
    "Aardwolf",
    "Biberkänguru",
    "Flusspferd",
    "Biber",
    "Bisamratte",
    "Dachsbeutel",
    "Kaninchenkänguru",
    "Potoroo",
    "Phalanger",
    "Fettschwanzkänguru",
    "Rüsselratte",
    "Beutelhase",
    "Beutelmaus",
    "Kurzschnauzenbeutelratte",
    "Nacktnasenwombat",
    "Südamerikanischer O",
    "",
];
let länder = [
    { country: "Afghanistan", capital: "Kabul" },
    { country: "Albanien", capital: "Tirana" },
    { country: "Algerien", capital: "Algier" },
    { country: "Andorra", capital: "Andorra-la-Vella" },
    { country: "Angola", capital: "Luanda" },
    { country: "AntiguaUndBarbuda", capital: " St. John's" },
    { country: "Argentinien", capital: "Buenos Aires" },
    { country: "Armenien", capital: "Eriwan" },
    { country: "Aserbaidschan", capital: "Baku" },
    { country: "Australien", capital: "Canberra" },
    { country: "Österreich", capital: "Wien" },
    { country: "Bahrain", capital: "Manama" },
    { country: "Bangladesch", capital: "Dhaka" },
    { country: "Barbados", capital: "Bridgetown" },
    { country: "Weißrussland", capital: "Minsk" },
    { country: "Belgien", capital: "Brüssel" },
    { country: "Belize", capital: "Belmopan" },
    { country: "Benin", capital: "Porto-Novo_(offiziell)" },
    { country: "Bhutan", capital: "Thimphu" },
    { country: "Bolivien", capital: " La Paz (administrativ)" },
    { country: "BosnienHerzegowina", capital: "Sarajevo" },
    { country: "Botsuana", capital: "Gaborone" },
    { country: "Brasilien", capital: "Brasília" },
    { country: "Brunei", capital: "Bandar Seri Begawan" },
    { country: "Bulgarien", capital: "Sofia" },
    { country: "BurkinaFaso", capital: "Ouagadougou" },
    { country: "Burundi", capital: "Bujumbura" },
    { country: "Kambodscha", capital: "Phnom Penh" },
    { country: "Kamerun", capital: "Yaoundé" },
    { country: "Kanada", capital: "Ottawa" },
    { country: "KapVerde", capital: "Praia" },
    { country: "ZentralAfrikanischeRepublik", capital: "Bangui" },
    { country: "Tschad", capital: "N_Djamena" },
    { country: "Chile", capital: "Santiago" },
    { country: "China", capital: "Peking (als Beijing in Mandarin)" },
    { country: "Kolumbien", capital: "Bogotá" },
    { country: "Komoren", capital: "Moroni" },
    { country: "Kongo", capital: "Brazzaville" },
    { country: "CostaRica", capital: "San José" },
    { country: "Kroatien", capital: "Zagreb" },
    { country: "Kuba", capital: "Havanna" },
    { country: "Zypern", capital: "Nikosia" },
    { country: "TschechischeRepublik", capital: "Prag" },
    { country: "Dänemark", capital: "Kopenhagen" },
    { country: "Dschibuti", capital: "Dschibuti Stadt" },
    { country: "Dominica", capital: "Roseau" },
    { country: "DominikanischeRepublik", capital: "Santo Domingo" },
    { country: "Ecuador", capital: "Quito" },
    { country: "Ägypten", capital: "Kairo" },
    { country: "ElSalvador", capital: "San Salvador" },
    { country: "Äquatorialguinea", capital: "Malabo" },
    { country: "Eritrea", capital: "Asmara" },
    { country: "Estland", capital: "Tallinn" },
    { country: "Äthiopien", capital: "Addis Abeba" },
    { country: "Fidschi", capital: "Suva" },
    { country: "Finnland", capital: "Helsinki" },
    { country: "Frankreich", capital: "Paris" },
    { country: "Gabun", capital: "Libreville" },
    { country: "Gambia", capital: "Banjul" },
    { country: "Georgien", capital: "Tiflis" },
    { country: "Deutschland", capital: "Berlin" },
    { country: "Ghana", capital: " Accra" },
    { country: "Griechenland", capital: "Athen" },
    { country: "Grenada", capital: 'St. George"s' },
    { country: "Guatemala", capital: "Guatemala Stadt" },
    { country: "Guinea", capital: "Conakry" },
    { country: "GuineaBissau", capital: "Bissau" },
    { country: "Guyana", capital: "Georgetown" },
    { country: "Haiti", capital: "Port-au-Prince" },
    { country: "Honduras", capital: "Tegucigalpa" },
    { country: "Hongkong", capital: "Hongkong" },
    { country: "Ungarn", capital: "Budapest" },
    { country: "Island", capital: "Reykjavik" },
    { country: "Indien", capital: "Neu-Delhi" },
    { country: "Indonesien", capital: "Jakarta" },
    { country: "Iran", capital: "Teheran" },
    { country: "Irak", capital: "Bagdad" },
    { country: "Irland", capital: "Dublin" },
    { country: "Israel", capital: "Jerusalem" },
    { country: "Italien", capital: " Rom" },
    { country: "Elfenbeinküste", capital: "Yamoussoukro" },
    { country: "Jamaika", capital: "Kingston" },
    { country: "Japan", capital: "Tokio" },
    { country: "Jordanien", capital: "Amman" },
    { country: "Kasachstan", capital: "Nur Sultan" },
    { country: "Kenia", capital: "Nairobi" },
    { country: "Kiribati", capital: "Tarawa" },
    { country: "Nordkorea", capital: "Pjöngjang" },
    { country: "Südkorea", capital: "Seoul" },
    { country: "Kosovo", capital: "Pristina" },
    { country: "Kuwait", capital: "Kuwait-Stadt" },
    { country: "Kirgisistan", capital: "Biskek" },
    { country: "Laos", capital: "Vientiane" },
    { country: "Lettland", capital: "Riga" },
    { country: "Libanon", capital: "Beirut" },
    { country: "Lesotho", capital: "Maseru" },
    { country: "Liberia", capital: "Monrovia" },
    { country: "Libyen", capital: "Tripolis" },
    { country: "Liechtenstein", capital: "Vaduz" },
    { country: "Litauen", capital: "Vilnius" },
    { country: "Luxemburg", capital: "Luxemburg" },
    { country: "Macau", capital: "Macau" },
    { country: "Mazedonien", capital: "Skopje" },
    { country: "Madagaskar", capital: "Antananarivo" },
    { country: "Malawi", capital: "Lilongwe" },
    { country: "Malaysia", capital: "Kuala Lumpur" },
    { country: "Malediven", capital: "Malé" },
    { country: "Mali", capital: "Bamako" },
    { country: "Malta", capital: "Valletta" },
    { country: "Marshallinseln", capital: "Majuro" },
    { country: "Mauretanien", capital: "Nouakchott" },
    { country: "Mauritius", capital: "Port Louis" },
    { country: "Mexiko", capital: "Mexiko-Stadt" },
    { country: "Mikronesien", capital: "Palikir" },
    { country: "Moldawien", capital: "Chisinau" },
    { country: "Monaco", capital: "Monaco" },
    { country: "Mongolei", capital: "Ulaanbaatar" },
    { country: "Montenegro", capital: "Podgorica" },
    { country: "Marokko", capital: "Rabat" },
    { country: "Mosambik", capital: "Maputo" },
    { country: "Myanmar", capital: "Naypyidaw" },
    { country: "Namibia", capital: "Windhoek" },
    { country: "Nauru", capital: "Yaren" },
    { country: "Nepal", capital: "Kathmandu" },
    { country: "Niederlande", capital: "Amsterdam" },
    { country: "Neuseeland", capital: "Wellington" },
    { country: "Nicaragua", capital: "Managua" },
    { country: "Niger", capital: "Niamey" },
    { country: "Nigeria", capital: "Abuja" },
    { country: "Norwegen", capital: "Oslo" },
    { country: "Oman", capital: "Maskat" },
    { country: "Pakistan", capital: "Islamabad" },
    { country: "Palau", capital: "Melekeok" },
    { country: "Panama", capital: "Panama Stadt" },
    { country: "Papua_Neuguinea", capital: "Port Moresby" },
    { country: "Paraguay", capital: "Asunción" },
    { country: "Peru", capital: " Lima" },
    { country: "Philippinen", capital: "Manila" },
    { country: "Polen", capital: "Warschau" },
    { country: "Portugal", capital: "Lissabon" },
    { country: "Katar", capital: "Doha" },
    { country: "Rumänien", capital: "Bukarest" },
    { country: "Russland", capital: "Moskau" },
    { country: "Ruanda", capital: "Kigali" },
    { country: "Saint_Kitts_Nevis", capital: "Basseterre" },
    { country: "Saint_Lucia", capital: "Castries" },
    { country: "Saint_Vincent_die_Grenadinen", capital: "Kingstown" },
    { country: "Samoa", capital: "Apia" },
    { country: "San_Marino", capital: "San Marino" },
    { country: "Sao_Tome_Principe", capital: "Sao Tome" },
    { country: "Saudi_Arabien", capital: "Riad" },
    { country: "Senegal", capital: "Dakar" },
    { country: "Serbien", capital: "Belgrad" },
    { country: "Seychellen", capital: "Victoria" },
    { country: "Sierra_Leone", capital: "Freetown" },
    { country: "Singapur", capital: "Singapur" },
    { country: "Slowakei", capital: "Bratislava" },
    { country: "Slovenien", capital: "Ljubljana" },
    { country: "Salomonen", capital: "Honiara" },
    { country: "Somalia", capital: "Mogadischu" },
    { country: "Südafrika", capital: "Pretoria (administrative Hauptstadt)" },
    { country: "Südsudan", capital: "Juba" },
    { country: "Spanien", capital: "Madrid" },
    { country: "Sri_Lanka", capital: "Sri Jayawardenepura Kotte" },
    { country: "Sudan", capital: "Khartum" },
    { country: "Surinam", capital: "Paramaribo" },
    { country: "Swasiland", capital: "Mbabane" },
    { country: "Schweden", capital: "Stockholm" },
    { country: "Schweiz", capital: "Bern" },
    { country: "Syrien", capital: "Damaskus" },
    { country: "Taiwan", capital: "Taipeh" },
    { country: "Tadschikistan", capital: "Duschanbe" },
    { country: "Tansania", capital: "Dodoma" },
    { country: "Thailand", capital: "Bangkok" },
    { country: "Osttimor", capital: " Dili" },
    { country: "Togo", capital: "Lomé" },
    { country: "Tonga", capital: "Nuku,alofa" },
    { country: "Trinidad_Tobago", capital: "Port of Spain" },
    { country: "Tunesien", capital: "Tunis" },
    { country: "Türkei", capital: "Ankara" },
    { country: "Turkmenistan", capital: "Ashgabat" },
    { country: "Tuvalu", capital: "Funafuti" },
    { country: "Uganda", capital: "Kampala" },
    { country: "Vereinigte_Arabische_Emirate", capital: "Abu Dhabi" },
    { country: "Großbritannien", capital: "London" },
    { country: "USA", capital: " Washington, D.C." },
    { country: "Uruguay", capital: "Montevideo" },
    { country: "Usbekistan", capital: "Taschkent" },
    { country: "Vanuatu", capital: " Port Vila" },
    { country: "Vatikanstadt", capital: "Vatikanstadt" },
    { country: "Venezuela", capital: "Caracas" },
    { country: "Vietnam", capital: "Hanoi" },
    { country: "Jemen", capital: "Sanaa" },
    { country: "Zambia", capital: "Lusaka" },
    { country: "Simbabwe", capital: "Harare" },
    { country: "Qatar(Katar)", capital: "Doha" },
    { country: "Yamen", capital: "Sana'a" },
    { country: "Xuzhou", capital: "China" },
    { country: "Xiamen", capital: "China" },
];
let berufe = [
    "Arzt/Ärztin",
    "Lehrer/Lehrerin",
    "Ingenieur/Ingenieurin",
    "Krankenschwester/Krankenpfleger",
    "Anwalt/Anwältin",
    "Architekt/Architektin",
    "Buchhalter/Buchhalterin",
    "Schriftsteller/Schriftstellerin",
    "Programmierer/Programmiererin",
    "Designer/Designerin",
    "Handwerker/Handwerkerin",
    "Verkäufer/Verkäuferin",
    "Koch/Köchin",
    "Polizist/Polizistin",
    "Künstler/Künstlerin",
    "Musiker/Musikerin",
    "Psychologe/Psychologin",
    "Zahnarzt/Zahnärztin",
    "Fotograf/Fotografin",
    "Journalist/Journalistin",
    "Archäologe/Archäologin",
    "Biologe/Biologin",
    "Xerox-Kopierer-Techniker",
    "XML-Entwickler",
    "Xylofonist",
    "X-Ray-Techniker",
    "Chemiker",
    "Mathematiker",
    "Optiker/in",
    "Orthopädietechniker/in",
    "Orthoptist/in",
    "Onkologe/Onkologin",
    "Organisationsentwickler/in",
    "Objektmanager/in",
    "Offsetdrucker/in",
    "Opernsänger/in",
    "Osteopath/in",
    "Obstbauer",
    "Physiker",
    "Astronom",
    "Geologin",
    "Geographin",
    "Meteorologe",
    "Ökonomin",
    "Soziologe",
    "Historikerin",
    "Anthropologe",
    "Linguistin",
    "Sozialarbeiter",
    "Umweltwissenschaftler",
    "Agrarwissenschaftler",
    "Krankenhausadministrator",
    "Betriebswirt",
    "Steuerberater",
    "Elektrikerin",
    "Klempnerin",
    "Zimmermann",
    "Maurer",
    "Tischler",
    "Schneider",
    "Metzger",
    "Bäcker",
    "Friseu",
    "Kosmetiker",
    "Reiseleiter",
    "Hotelmanager",
    "Restaurantbesitzer",
    "Weinbauer",
    "Landschaftsgärtner",
    "Mechaniker/",
    "Automechanike",
    "Flugzeugmechaniker",
    "Schiffsbauer",
    "Schmied",
    "Goldschmied",
    "Juwelier",
    "Textildesigner",
    "Modedesigner",
    "Schauspieler",
    "Regisseur",
    "Kameramann",
    "Stuntman",
    "Make-up Artist",
    "Maskenbildnerin",
    "Filmproduzentin",
    "Drehbuchautorin",
    "Sounddesignerin",
    "Grafikdesignerin",
    "Werbetexterin",
    "Marketingmanagerin",
    "Unternehmensberaterin",
    "Personalberaterin",
    "Versicherungsvertreterin",
    "Banker",
    "Vermögensverwalter",
    "Finanzanalyst/Finanzanalystin",
    "Aktienhändler/Aktienhändlerin",
    "Immobilienmakler/Immobilienmaklerin",
    "Bauingenieur/Bauingenieurin",
    "Umweltingenieur/Umweltingenieurin",
    "Maschinenbauingenieur/Maschinenbauingenieurin",
    "Elektroingenieur/Elektroingenieurin",
    "Luft- und Raumfahrtingenieur/Luft- und Raumfahrtingenieurin",
    "Informatiker/Informatikerin",
    "Webentwickler/Webentwicklerin",
    "Datenbankadministrator/Datenbankadministratorin",
    "Netzwerkadministrator/Netzwerkadministratorin",
    "Systemadministrator/Systemadministratorin",
    "IT-Sicherheitsexperte/IT-Sicherheitsexpertin",
    "Unternehmensjurist/Unternehmensjuristin",
    "Arbeitsrechtler/Arbeitsrechtlerin",
    "Strafverteidiger/Strafverteidigerin",
    "Notar/Notarin",
    "Steuerfachmann/Steuerfachfrau",
    "Hausmeister/Hausmeisterin",
    "Gärtner/Gärtnerin",
    "Tierarzt/Tierärztin",
    "Tierpfleger/Tierpflegerin",
    "Lehrer für spezielle Bedürfnisse/Lehrerin für spezielle Bedürfnisse",
    "Sozialpädagoge/Sozialpädagogin",
    "Erzieher/Erzieherin",
    "Hebamme",
    "Physiotherapeut/Physiotherapeutin",
    "Ergotherapeut/Ergotherapeutin",
    "Logopäde/Logopädin",
    "Krankenhausapotheker/Krankenhausapothekerin",
    "Apotheker/Apothekerin",
    "Laborant/Laborantin",
    "Chemielaborant/Chemielaborantin",
    "Biotechnologe/Biotechnologin",
    "Ökotrophologe/Ökotrophologin",
    "Ernährungsberater/Ernährungsberaterin",
    "Sporttrainer/Sporttrainerin",
    "Personal Trainer/Personal Trainerin",
    "Fitnesstrainer/Fitnesstrainerin",
    "Yoga-Lehrer/Yoga-Lehrerin",
    "Pilates-Lehrer/Pilates-Lehrerin",
    "Zumba-Instruktor/Zumba-Instruktorin",
    "DJ",
    "Qualitätskontrolleur/in",
    "Quantenphysiker/in",
    "Quereinsteiger/in",
    "Quick-Response-Manager/in",
    "Quartiermeister/in",
    "Quotenfrau/-mann",
    "Qualitätsmanager/in",
    "Querdenker/in",
    "Qualifizierungstrainer/in",
    "Quelltextprogrammierer/in",
    "Eventplaner/Eventplanerin",
    "Hochzeitsplaner/Hochzeitsplanerin",
    "Rechtsanwaltsfachangestellte/Rechtsanwaltsfachangestellter",
    "Steuerfachangestellte/Ste",
    "",
];
let autos = [
    "Acura",
    "Xenia",
    "Xpeng",
    "Opel ",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Qiantu K50",
    "Bentley",
    "BMW",
    "Bugatti",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "Genesis",
    "GMC",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Koenigsegg",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "UAZ Patriot",
    "Ultima GTR",
    "Unicorn Ascot",
    "Unimog",
    "Uriel Ventris",
    "Urbee 2",
    "URSUS C-385",
    "UAZ-469",
    "UMM Alter II",
    "Union Cycliste Internationale (UCI)",
    "Maserati",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "Mini",
    "Mitsubishi",
    "Nissan",
    "Pagani",
    "Peugeot",
    "Pininfarina",
    "Plymouth",
    "Polestar",
    "Pontiac",
    "Porsche",
    "Ram",
    "Renault",
    "Rimac",
    "Rolls-Royce",
    "Saab",
    "Saleen",
    "Saturn",
    "Scion",
    "Seat",
    "Skoda",
    "Smart",
    "Spyker",
    "Yema",
    "Youngman",
    "Yutong",
    "SsangYong",
    "Subaru",
    "Suzuki",
    "Tatra",
    "Tesla",
    "Toyota",
    "Triumph",
    "TVR",
    "Vauxhall",
    "Volkswagen",
    "Volvo",
    "Wiesmann",
    "W Motors",
    "Zenvo",
    "AC Cars",
    "Adler",
    "Aixam",
    "Alpina",
    "Alta",
    "AM General",
    "Ariel",
    "Artega",
    "Ascari",
    "Autobianchi",
    "Autovia",
    "BAC",
    "Barkas",
    "Beauford",
    "Bitter",
    "Borgward",
    "Brabus",
    "Bricklin",
    "Bristol",
    "Bufori",
    "BYD",
    "Cagiva",
    "Callaway",
    "Caterham",
    "Chang'an",
    "Chatenet",
    "Chery",
    "Chevrolet Corvette",
    "Chrysler Crossfire",
    "Cisitalia",
    "Cizeta",
    "Connaught",
    "Cord",
    "Covini",
    "Dacia",
    "Daewoo",
    "Daihatsu",
    "Daimler",
    "Datsun",
    "De Tomaso",
    "Delage",
    "Delahaye",
    "Denzel",
    "DeSoto",
    "Devon",
    "DKW",
    "Donkervoort",
    "Eagle",
    "Edsel",
    "Elfin",
    "Faraday Future",
    "FAW",
    "Fendt",
    "Fisker",
    "Frazer Nash",
    "GAZ",
    "Geo",
    "Ginetta",
    "Gumpert",
    "Haval",
    "Hennessey",
    "Hillman",
    "Hindustan",
    "Holden",
    "Hudson",
    "Humber",
    "IFA",
    "Imperial",
    "Innocenti",
    "Intermeccanica",
    "Invicta",
    "Isdera",
    "Iso",
    "Isotta Fraschini",
    "Italdesign",
    "Iveco",
    "Jannarelly",
    "Jensen",
    "Jowett",
    "Lorraine-Dietrich",
    "Luxgen",
    "Mahindra",
    "Marcos",
    "Maruti",
    "Maybach",
    "Mazda Autozam",
    "McLaren Senna",
];
let pflanzen = [
    "Ahornbaum",
    "Zierlauch ",
    "Zitronenbaum ",
    "Zierquitte ",
    "Zaubernuss ",
    "Zimtbaum ",
    "Zucchini ",
    "Zwergmispel ",
    "Zwergginster ",
    "Zitronenmelisse ",
    "Zypressen",
    "Ananas",
    "Aloe Vera",
    "Apfelbaum",
    "Avocado",
    "Bambus",
    "Bananenstaude",
    "Basilikum",
    "Begonie",
    "Birnbaum",
    "Blaubeere",
    "Blumenkohl",
    "Brombeere",
    "Buschbohne",
    "Buschpfeffer",
    "Chili",
    "Dahlie",
    "Dattelpalme",
    "Distel",
    "Efeu",
    "Eichenbaum",
    "Eisenhut",
    "Erdbeere",
    "Eukalyptus",
    "Farn",
    "Feige",
    "Fenchel",
    "Fingerhut",
    "Flieder",
    "Gerbera",
    "Gerste",
    "Ginster",
    "Goldregen",
    "Gras",
    "Usambaraveilchen",
    "Urwaldrebe",
    "Ufer-Wolfstrapp",
    "Ulme (Ulmus)",
    "Ufer-Binse (Juncus)",
    "Usambarazwergpalme ",
    "Unsterblichkeitskraut ",
    "Unterseeische Grasnelke ",
    "Urwaldpfeffer ",
    "Gurke",
    "Xanthorrhoea",
    "Xeranthemum",
    "Xyris",
    "Xenophyllum ",
    "Haselnussbaum",
    "Heidekraut",
    "Himbeere",
    "Hortensie",
    "Hyazinthe",
    "Ingwer",
    "Jasmin",
    "Johannisbeere",
    "Kaktus",
    "Kamille",
    "Kapernstrauch",
    "Kartoffel",
    "Kiefernbaum",
    "Kirschbaum",
    "Knoblauch",
    "Kohl",
    "Krokus",
    "Kürbis",
    "Lavendel",
    "Leinsamen",
    "Löwenzahn",
    "Magnolie",
    "Malve",
    "Mandelbaum",
    "Mango",
    "Maulbeere",
    "Meerrettich",
    "Melone",
    "Minze",
    "Mohrrübe",
    "Narzisse",
    "Nelke",
    "Olive",
    "Orchidee",
    "Paprika",
    "Paprika",
    "Papaya",
    "Papyrus",
    "Passionsblume",
    "Pfefferminze",
    "Pflaumenbaum",
    "Pinie",
    "Quitte",
    "Radieschen",
    "Raps",
    "Rhabarber",
    "Rhododendron",
    "Ringelblume",
    "Rosmarin",
    "Rotklee",
    "Safran",
    "Salbei",
    "Schachtelhalm",
    "Schlehdorn",
    "Schneeglöckchen",
    "Schwarzer Holunder",
    "Sonnenblume",
    "Spargel",
    "Spinat",
    "Stiefmütterchen",
    "Tabakpflanze",
    "Thymian",
    "Tomate",
    "Traubenbaum",
    "Wacholder",
    "Yucca-Palme",
    "Yakushi-Girlandenblume",
    "Ysop",
    "Yelapa-Salbei",
    "Yilan-Kiefer",
    "Ylang-Ylang-Baum",
    "Yebisu-Bambus",
    "Yerba-Buena",
    "Yellowwood-Baum ",
    "Yoko-Bambus",
    "",
];
let kleidungsnamen = [
    "Hemd",
    "Bluse",
    "T-Shirt",
    "Polohemd",
    "Hoodie",
    "Jacke",
    "Mantel",
    "Blazer",
    "Weste",
    "Pullover",
    "Strickjacke",
    "Tanktop",
    "Langarmshirt",
    "Sweatshirt",
    "Regenjacke",
    "Windbreaker",
    "Bomberjacke",
    "Anorak",
    "Parka",
    "Poncho",
    "Kimono",
    "Kleid",
    "Tunika",
    "Abendkleid",
    "Cocktailkleid",
    "Brautkleid",
    "Ballkleid",
    "Sommerkleid",
    "Maxikleid",
    "Minikleid",
    "Midikleid",
    "Skaterkleid",
    "Wickelkleid",
    "Etuikleid",
    "Shiftkleid",
    "Hemdblusenkleid",
    "Blusenkleid",
    "Jeans",
    "Shorts",
    "Bermudas",
    "Caprihose",
    "Stoffhose",
    "Anzugshose",
    "Chino",
    "Leggings",
    "Jeggings",
    "Cargo-Hose",
    "Jogginghose",
    "Trainingshose",
    "Sporthose",
    "Badeanzug",
    "Bikini",
    "Badehose",
    "Boardshorts",
    "Monokini",
    "Tankini",
    "Strickpullover",
    "Rollkragenpullover",
    "Fleecejacke",
    "Lederjacke",
    "Daunenjacke",
    "Steppjacke",
    "Regenmantel",
    "Trenchcoat",
    "Poncho",
    "Bolero",
    "Schal",
    "Halstuch",
    "Krawatte",
    "Fliege",
    "Handschuhe",
    "Mütze",
    "Kappe",
    "Hut",
    "Sonnenbrille",
    "Gürtel",
    "Hosenträger",
    "Socken",
    "Strumpfhose",
    "Legwarmers",
    "Stiefel",
    "Sportschuhe",
    "Sneakers",
    "Sandalen",
    "Flip-Flops",
    "Pumps",
    "High Heels",
    "Keilabsatz",
    "Plateauschuhe",
    "Ballerinas",
    "Loafers",
    "Bootsschuhe",
    "Espadrilles",
    "Wanderschuhe",
    "Arbeitsschuhe",
    "Sicherheitsschuhe",
    "Clogs",
    "Crocs",
    "Hausschuhe",
    "Regenstiefel",
];
let farbnamen = [
    "Altrosa",
    "Amaranth",
    "Amber",
    "Anthrazit",
    "Apfelgrün",
    "Apricot",
    "Aquamarin",
    "Aschgrau",
    "Azurblau",
    "Rot",
    "Blau",
    "Grün",
    "Gelb",
    "Orange",
    "Lila",
    "Pink",
    "Braun",
    "Grau",
    "Schwarz",
    "Weiß",
    "Beige",
    "Türkis",
    "Olivgrün",
    "Dunkelgrün",
    "Hellgrün",
    "Dunkelblau",
    "Hellblau",
    "Dunkelrot",
    "Hellrot",
    "Zitronengelb",
    "Limettengrün",
    "Lavendel",
    "Marineblau",
    "Kastanienbraun",
    "Mahagoni",
    "Gold",
    "Silber",
    "Kupfer",
    "Zinnoberrot",
    "Scharlachrot",
    "Azurblau",
    "Babyblau",
    "Babyrosa",
    "Blassgrün",
    "Blassgelb",
    "Blasslila",
    "Blassorange",
    "Blassrot",
    "Bordeaux",
    "Dunkelgrau",
    "Hellgrau",
    "Karamell",
    "Kobaltblau",
    "Magenta",
    "Mokka",
    "Olivbraun",
    "Pfirsich",
    "Rubinrot",
    "Sand",
    "Schiefergrau",
    "Smaragdgrün",
    "Tannengrün",
    "Terrakotta",
    "Türkisblau",
    "Violett",
    "Ziegelrot",
    "Apfelgrün",
    "Aquamarin",
    "Babyblau",
    "Babygrün",
    "Babyviolett",
    "Dunkelbraun",
    "Dunkelviolett",
    "Eierschale",
    "Flieder",
    "Hellgelb",
    "Hellrosa",
    "Hellviolett",
    "Indigo",
    "Kirschrot",
    "Knallrot",
    "Lavendelblau",
    "Maigrün",
    "Olivgrau",
    "Pflaume",
    "Rauchblau",
    "Rostrot",
    "Salbeigrün",
    "Schwarzbraun",
    "Senfgelb",
    "Stahlblau",
    "Taupe",
    "Vanillegelb",
    "Waldgrün",
    "Weinrot",
    "Zartblau",
    "Zartgrün",
    "Zartorange",
    "Zartrosa",
    "Zartviolett",
    "Zimtbraun",
    "Azalee",
    "Blaugrau",
    "Blassrosa",
    "Bronze",
    "Dunkelgrasgrün",
    "Dunkelolivgrün",
    "Farngrün",
    "Heidekrautviolett",
];
let materialnamen = [
    "Baumwolle",
    "Wolle",
    "Leinen",
    "Seide",
    "Samt",
    "Leder",
    "Kunstleder",
    "Wildleder",
    "Denim",
    "Cord",
    "Polyester",
    "Viskose",
    "Acryl",
    "Polyamid",
    "Kaschmir",
    "Mohair",
    "Angora",
    "Alpaka",
    "Merinowolle",
    "Kaschmirwolle",
    "Kamelhaar",
    "Ziegenleder",
    "Schafleder",
    "Rindsleder",
    "Wildlederimitat",
    "Pelz",
    "Fell",
    "Fleece",
    "Spitze",
    "Organza",
    "Satin",
    "Brokat",
    "Chiffon",
    "Jersey",
    "Strickstoff",
    "Batikstoff",
    "Leopardenmuster",
    "Zebra-Muster",
    "Schlangenhautmuster",
    "Karomuster",
    "Streifenmuster",
    "Punkt-Muster",
    "Blumenmuster",
    "Paisleymuster",
    "Polka-Dot-Muster",
    "Hahnentritt-Muster",
    "Tweed",
    "Bouclé",
    "Jacquard",
    "WaffelpiquéKork",
    "Segeltuch",
    "Hanf",
    "Jute",
    "Canvas",
    "Veloursleder",
    "Mikrofaser",
    "Neopren",
    "Gore-Tex",
    "Softshell",
    "Ripstop",
    "Twill",
    "Popeline",
    "Chambray",
    "Voile",
    "Batist",
    "Taft",
    "Organischen Baumwolle",
    "Hanf-Baumwollmischung",
    "Leinen-Baumwollmischung",
    "Seiden-Baumwollmischung",
    "Jersey-Baumwollmischung",
    "Wolle-Leinen-Mischung",
    "Wolle-Seiden-Mischung",
    "Nylon",
    "Elasthan",
    "Spandex",
    "Gummi",
    "Latex",
    "Lurex",
    "Metallic-Stoff",
    "Plüsch",
    "Velours",
    "Lammfell",
    "Schaffell",
    "Mohair-Wolle-Mischung",
    "Leopardenfellimitat",
    "Zebraprint-Fellimitat",
    "Leopardenprint-Wildlederimitat",
    "Schlangenlederimitat",
    "Krokodillederimitat",
    "Straußenlederimitat",
    "Bambus",
    "Holz",
    "Keramik",
    "Laminat",
    "Vinyl",
    "Marmor",
    "Granit",
    "Glasfaser",
];
let sportarten = [
    "American Football",
    "Baseball",
    "Basketball",
    "Boxen",
    "Cricket",
    "Eislaufen",
    "Eiskunstlauf",
    "Eisschnelllauf",
    "Fechten",
    "Feldhockey",
    "Fußball",
    "Golf",
    "Handball",
    "Inline-Skaten",
    "Judo",
    "Kanu",
    "Karate",
    "Kegeln",
    "Klettern",
    "Kugelstoßen",
    "Langlauf",
    "Leichtathletik",
    "Mountainbiking",
    "Nordic Walking",
    "Paintball",
    "Pferderennen",
    "Polo",
    "Racquetball",
    "Rennradfahren",
    "Rudern",
    "Rugby",
    "Schach",
    "Schwimmen",
    "Skateboarden",
    "Skifahren",
    "Snowboarden",
    "Squash",
    "Surfen",
    "Taekwondo",
    "Tischtennis",
    "Triathlon",
    "Volleyball",
    "Wakeboarding",
    "Wasserball",
    "Wasserski",
    "Windsurfen",
    "Wrestling",
    "Yoga",
    "Badminton",
    "Bogenschießen",
    "Bowling",
    "Bridge",
    "Curling",
    "Darts",
    "Drachenbootfahren",
    "Fallschirmspringen",
    "Federball",
    "Fischen",
    "Flag Football",
    "Freeskiing",
    "Freestyle-Skifahren",
    "Gleitschirmfliegen",
    "Handbike",
    "Kajakfahren",
    "Kitesurfen",
    "Marathon",
    "Mountainboarding",
    "Nordic Combined",
    "Paragliding",
    "Pistolenschießen",
    "Quadfahren",
    "Rafting",
    "Ringen",
    "Rollstuhlbasketball",
    "Rollstuhltennis",
    "Rugby League",
    "Rugby Union",
    "Schießen",
    "Schnorcheln",
    "Segeln",
    "Skatecross",
    "Skibergsteigen",
    "Skilanglauf-Biathlon",
    "Skispringen",
    "Speedskating",
    "Stand-Up-Paddling",
    "Streetball",
    "Synchroschwimmen",
    "Tanzsport",
    "Teamgym",
    "Tennis",
    "Trampolinspringen",
    "Ultimate Frisbee",
    "Volleyballbeach",
    "Wassergymnastik",
    "Wasserpolo",
    "Windsurfen",
    "Wing Tsun",
    "Wrestling",
    "ZumbaAikido",
    "Apnoetauchen",
    "Aquabike",
    "Aquajogging",
    "Ballett",
    "Bodybuilding",
    "Bouldern",
    "Bridge",
    "Capoeira",
    "Cheerleading",
    "Crossfit",
    "Cyclocross",
    "Dartpfeilwerfen",
    "Eisangeln",
    "Fahrradpolo",
    "Feldfaustball",
    "Finswimming",
    "Flagfootball",
    "Fliegenfischen",
    "Footbag",
    "Freestyle-Fußball",
    "Freestyle-Skateboarding",
    "Gehen",
    "Gymnastik",
    "Hacky Sack",
    "Hanggliding",
    "Heißluftballonfahren",
    "Hürdenlauf",
    "Indiaca",
    "Jai Alai",
    "Jiu-Jitsu",
    "Jogging",
    "Judo",
    "Kanupolo",
    "Kendo",
    "Kitesurfen",
    "Klettern",
    "Kugelstoßen",
    "Langhanteltraining",
    "Le Parkour",
    "Luftgewehrschießen",
    "Marathonlauf",
    "Minigolf",
    "Mountainbike-Triathlon",
    "Nordic Fitness",
    "Orientierungslauf",
    "Padelsport",
    "Paintball",
    "Parkour",
    "Parkour/Freerunning",
    "Pétanque",
    "Pilates",
    "Powerlifting",
    "Qigong",
    "Radball",
    "Radpolo",
    "Radsport",
    "Reiten",
    "Rhythmisches Sportgymnastik",
    "Riesenslalom",
    "Rock Climbing",
    "Rope Skipping",
    "Rugby League",
    "Rugby Union",
    "Rundstreckenrennen",
    "Salsa",
    "Schachboxen",
    "Schießen",
    "Schneeschuhwandern",
    "Schnorcheln",
    "Schwertkampf",
    "Segelfliegen",
    "Segeln",
    "Selbstverteidigung",
    "Skateboarden",
    "Skijöring",
    "Slamball",
    "Snooker",
    "Snowbiking",
    "Snowkiting",
    "Snowshoeing",
    "Softball",
    "Spinning",
    "Squash",
    "Street Workout",
    "Surfen",
    "Taekwondo",
    "Tanzen",
    "Tennis",
    "Tischfußball",
    "Tourenski",
    "Trailrunning",
    "Trampolinturnen",
    "Turnen",
    "Ultimate Frisbee",
    "Unterwasserhockey",
    "Wakeboarding",
    "Wasserski",
    "Wing Chun",
    "Yoga",
];

let vierbDeu = [
    "Abholen",
    "Absagen",
    "Abstimmen",
    "Anfangen",
    "Anhalten",
    "Ankommen",
    "Anmelden",
    "Anrufen",
    "Aufhören",
    "Aufmachen",
    "Aufstehen",
    "Ausfüllen",
    "Ausgehen",
    "Ausprobieren",
    "Aussteigen",
    "Backen",
    "Bauen",
    "Bedienen",
    "Bedienen",
    "Begrüßen",
    "Behalten",
    "Beobachten",
    "Beschreiben",
    "Besuchen",
    "Bewegen",
    "Bezahlen",
    "Bleiben",
    "Blockieren",
    "Blühen",
    "Brauchen",
    "Brennen",
    "Bringen",
    "Buchen",
    "Denken",
    "Diskutieren",
    "Drucken",
    "Einkaufen",
    "Einladen",
    "Einpacken",
    "Einschlafen",
    "Einsteigen",
    "Entdecken",
    "Entspannen",
    "Entscheiden",
    "Entwickeln",
    "Erklären",
    "Erreichen",
    "Essen",
    "Fahren",
    "Falten",
    "Feiern",
    "Fliegen",
    "Folgen",
    "Fotografieren",
    "Freuen",
    "Fühlen",
    "Gehen",
    "Gehören",
    "Gelten",
    "Genießen",
    "Gewinnen",
    "Grillen",
    "Haben",
    "Helfen",
    "Herstellen",
    "Hoffen",
    "Hören",
    "Informieren",
    "Interessieren",
    "Jagen",
    "Kaufen",
    "Kämpfen",
    "Klettern",
    "Kochen",
    "Kommen",
    "Konzentrieren",
    "Korrigieren",
    "Küssen",
    "Lächeln",
    "Laufen",
    "Leben",
    "Lernen",
    "Lieben",
    "Machen",
    "Mitbringen",
    "Mitkommen",
    "Mögen",
    "Nachdenken",
    "Öffnen",
    "Reisen",
    "Reservieren",
    "Schlafen",
    "Schreiben",
    "Schwimmen",
    "Sehen",
    "Spielen",
    "Sprechen",
    "Stehen",
    "Stören",
    "VerabschiedenVerändern",
    "Verbringen",
    "Vereinbaren",
    "Verkaufen",
    "Vermieten",
    "Verpassen",
    "Versuchen",
    "Verstehen",
    "Vertreten",
    "Verwenden",
    "Verzichten",
    "Vorbereiten",
    "Vorhaben",
    "Vorstellen",
    "Wählen",
    "Warten",
    "Waschen",
    "Wegwerfen",
    "Weinen",
    "Werben",
    "Werfen",
    "Wiederholen",
    "Wissen",
    "Wollen",
    "Wünschen",
    "Zählen",
    "Ziehen",
    "Zuhören",
    "Zuschauen",
    "Zuspätkommen",
    "Ablehnen",
    "Abschließen",
    "Ändern",
    "Anbieten",
    "Anfangen",
    "Anzeigen",
    "Auffordern",
    "Aufnehmen",
    "Aufpassen",
    "Ausschalten",
    "Aussprechen",
    "Austauschen",
    "Auswählen",
    "Befreien",
    "Befürchten",
    "Begegnen",
    "Begleiten",
    "Begründen",
    "Behandeln",
    "Beilegen",
    "Beispiele geben",
    "Bekanntmachen",
    "Benutzen",
    "Beraten",
    "Berichten",
    "Beschränken",
    "Beschweren",
    "Bestehen",
    "Bewerben",
    "Bewirken",
    "Bleiben",
    "Dauern",
    "Dienen",
    "Duschen",
    "Eignen",
    "Entfernen",
    "Entschuldigen",
    "Entspannen",
    "Enttäuschen",
    "Entwickeln",
    "Erfinden",
    "Erhalten",
    "Erkennen",
    "Erleben",
    "Erlernen",
    "Ersetzen",
    "Erwarten",
    "Erzählen",
    "Fassen",
    "Festlegen",
    "Festnehmen",
    "Finden",
    "Flüstern",
    "Fordern",
    "Fotografieren",
    "Freigeben",
    "Freuen",
    "Gelingen",
    "Gehorchen",
    "Gelten",
    "Genießen",
    "Geraten",
    "Geschickt sein",
    "Gewinnen",
    "Glauben",
    "Helfen",
    "Herstellen",
    "Hoffen",
    "Informieren",
    "Interessieren",
];
let länder2 = [];
let statt = [];
for (let i = 0; i < länder.length; i++) {
    länder2.push(länder[i].country);
    statt.push(länder[i].capital);

    function eingabePru(B, L, S, F, N, H, P, T, Br, A, K, FaR, M, V, Sp) {
        let punkte = 0;
        let inputLowerCase = B.toLowerCase();

        const suche = (inp, array) => {
            if (
                inp &&
                inp.toLowerCase().startsWith(inputLowerCase) &&
                array.join(",").toLowerCase().includes(inp.toLowerCase())
            ) {
                punkte +=10;
            }
        };
        suche(L, länder2);
        suche(S, statt);
        suche(F, flüsse);
        suche(N, namen);
        suche(H, haussHallt);
        suche(P, pflanzen);
        suche(T, tiere);
        suche(Br, berufe);
        suche(A, autos);
        suche(K, kleidungsnamen);
        suche(FaR, farbnamen);
        suche(M, materialnamen);
        suche(V, vierbDeu);
        suche(Sp, sportarten);

        console.log(punkte);
        return punkte;
    }
}
console.log(eingabePru("a","Afghanistan","Algier","Amazonas","Ava","Abfalleimer","Ahornbaum","Assel","Arzt/Ärztin","Audi","Krawatte","Apricot","Acryl","Absagen","American Football"));


//"a","Afghanistan","Algier","Amazonas","Ava","Abfalleimer","Ahornbaum",

//"Assel", "Arzt/Ärztin", "Audi", "Krawatte", "Apricot", "Acryl", "Absagen", "American Football"));